options {
  directory "/var/cache/bind";
  listen-on { any; };
  listen-on-v6 { any; };
  recursion no;
  allow-query { any; };
  allow-query-cache { none; };
  version "IZAKHONO DNS SECONDARY";
};

zone "izakhonoafrica.co.za" IN {
  type secondary;
  file "/var/lib/bind/izakhonoafrica.co.za.zone";
  primaries { dns-primary; };
};
