export type ControlPlaneCapability={id:string;name:string;purpose:string;ownedBoundary:string;externalAdapters:string[];reversible:boolean;liveClaimRequires:string[];status:'planned'|'ready'|'verified'|'blocked'};

export const CONTROL_PLANE_CAPABILITIES:ControlPlaneCapability[]=[
{id:'dns',name:'DNS Control',purpose:'Delegation, records, diagnostics and fallback routing.',ownedBoundary:'IZAKHONO DNS engine',externalAdapters:['Cloudflare DNS/registrar'],reversible:true,liveClaimRequires:['delegation_check','authoritative_answer_check'],status:'planned'},
{id:'reachability',name:'Public Reachability',purpose:'Detect public reachability, CGNAT and port constraints.',ownedBoundary:'IZAKHONO reachability diagnostics',externalAdapters:['upstream network','public probe'],reversible:true,liveClaimRequires:['external_probe_success'],status:'planned'},
{id:'tls',name:'TLS Control',purpose:'Certificate issuance, renewal and reverse-proxy termination.',ownedBoundary:'IZAKHONO certificate/reverse-proxy engine',externalAdapters:['ACME CA'],reversible:true,liveClaimRequires:['certificate_valid','https_health_check'],status:'planned'},
{id:'deploy',name:'Application Deployment',purpose:'Repeatable manifests, release verification and rollback.',ownedBoundary:'IZAKHONO deploy engine',externalAdapters:['Vercel','Netlify'],reversible:true,liveClaimRequires:['artifact_verified','runtime_health_check'],status:'planned'},
{id:'identity',name:'Identity & Secrets',purpose:'Tenant-scoped identity, credentials and secret references.',ownedBoundary:'IZAKHONO identity/security engine',externalAdapters:['external identity providers'],reversible:true,liveClaimRequires:['auth_check','secret_reference_check'],status:'planned'},
{id:'data',name:'Data & Object Storage',purpose:'Provision data stores with backup/restore boundaries.',ownedBoundary:'IZAKHONO data/object engines',externalAdapters:['Supabase/PostgreSQL','external object storage'],reversible:true,liveClaimRequires:['schema_check','write_read_check','restore_check'],status:'planned'},
{id:'mail',name:'Business Email',purpose:'Email DNS, mailbox and delivery workflow.',ownedBoundary:'IZAKHONO mail provisioning engine',externalAdapters:['mail provider'],reversible:true,liveClaimRequires:['mx_check','spf_check','dkim_check','smtp_delivery_check'],status:'planned'},
{id:'monitoring',name:'Observability',purpose:'Uptime, DNS, TLS and HTTP monitoring with audit evidence.',ownedBoundary:'IZAKHONO observability engine',externalAdapters:['external probes'],reversible:true,liveClaimRequires:['probe_success','alert_path_check'],status:'planned'},
{id:'backup',name:'Backup & Recovery',purpose:'Automated backups, restore verification and rollback evidence.',ownedBoundary:'IZAKHONO recovery engine',externalAdapters:['external storage fallback'],reversible:true,liveClaimRequires:['backup_created','restore_verified'],status:'planned'},
{id:'provisioning',name:'Payment-to-Provisioning',purpose:'Verified payment creates an idempotent provisioning job.',ownedBoundary:'IZAKHONO provisioner',externalAdapters:['iKhokha','PayFast'],reversible:true,liveClaimRequires:['payment_verified','job_created','provisioning_verified'],status:'planned'}
];

export function controlPlaneStatus(){const counts={planned:0,ready:0,verified:0,blocked:0};for(const c of CONTROL_PLANE_CAPABILITIES)counts[c.status]++;return {ownedFirst:true,noLiveClaimsWithoutEvidence:true,counts,capabilities:CONTROL_PLANE_CAPABILITIES};}
