export type DomainStatus = "pendingCreate" | "ok" | "clientHold" | "clientTransferProhibited" | "pendingTransfer" | "pendingDelete" | "redemptionPeriod";
export type Domain = { name:string; registrarId:string; registrantId:string; nameservers:string[]; status:DomainStatus; createdAt:string; updatedAt:string; expiresAt:string };
export type Contact = { id:string; name:string; email:string; organization?:string; country?:string };
export type Host = { name:string; addresses:string[] };
export type AuditEvent = { id:string; at:string; actor:string; action:string; objectType:string; objectId:string; before?:unknown; after?:unknown };
export interface RegistryStore { getDomain(name:string):Promise<Domain|undefined>; putDomain(domain:Domain):Promise<void>; getContact(id:string):Promise<Contact|undefined>; putContact(contact:Contact):Promise<void>; getHost(name:string):Promise<Host|undefined>; putHost(host:Host):Promise<void>; audit(event:AuditEvent):Promise<void>; }
export interface DnsProvider { publish(zone:string, records:unknown[]):Promise<void>; remove(zone:string):Promise<void>; verify?(zone:string):Promise<boolean>; }
export interface RdapProvider { verify(name:string):Promise<boolean>; }
export interface RegistryAdapter { availability(name:string):Promise<boolean>; register(domain:Domain):Promise<{transactionId:string;confirmed:boolean}>; renew(name:string,years:number):Promise<{transactionId:string;expiresAt:string}>; transfer(name:string,authCode:string):Promise<{transactionId:string}>; }
export function normalizeDomain(input:string){const n=input.trim().toLowerCase().replace(/\.$/,"");if(!/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$/.test(n))throw new Error("invalid domain");return n;}
export function canTransition(from:DomainStatus,to:DomainStatus){const a:Record<DomainStatus,DomainStatus[]>={pendingCreate:["ok","clientHold"],ok:["clientHold","clientTransferProhibited","pendingTransfer","pendingDelete"],clientHold:["ok","pendingDelete"],clientTransferProhibited:["ok","pendingTransfer"],pendingTransfer:["ok","clientTransferProhibited"],pendingDelete:["redemptionPeriod"],redemptionPeriod:["pendingDelete","ok"]};return a[from].includes(to);}
export async function createDomain(store:RegistryStore,input:Omit<Domain,"status"|"createdAt"|"updatedAt">,actor:string){const name=normalizeDomain(input.name);if(await store.getDomain(name))throw new Error("domain exists");const now=new Date().toISOString();const domain:Domain={...input,name,status:"pendingCreate",createdAt:now,updatedAt:now};await store.putDomain(domain);await store.audit({id:crypto.randomUUID(),at:now,actor,action:"domain.create",objectType:"domain",objectId:name,after:domain});return domain;}
export async function transitionDomain(store:RegistryStore,name:string,to:DomainStatus,actor:string){const current=await store.getDomain(normalizeDomain(name));if(!current)throw new Error("domain not found");if(!canTransition(current.status,to))throw new Error("invalid transition");const next={...current,status:to,updatedAt:new Date().toISOString()};await store.putDomain(next);await store.audit({id:crypto.randomUUID(),at:next.updatedAt,actor,action:"domain.transition",objectType:"domain",objectId:next.name,before:current,after:next});return next;}
