export type WorkerDomain="control"|"identity"|"security"|"data"|"search"|"social"|"media"|"music"|"commerce"|"finance"|"work"|"education"|"developer"|"cloud"|"growth"|"support"|"trust"|"mobility"|"travel"|"ai";
export type WorkerSpec={id:string;domain:WorkerDomain;mission:string;inputs:string[];outputs:string[];engines:string[];risk:"low"|"medium"|"high";reversible:boolean;humanGate?:string};
const W=(id:string,domain:WorkerDomain,mission:string,risk:"low"|"medium"|"high"="low",humanGate?:string):WorkerSpec=>({id,domain,mission,inputs:["job_input"],outputs:["job_output"],engines:[],risk,reversible:true,humanGate});
export const WORKERS:WorkerSpec[]=[
W("portfolio-orchestrator","control","Decompose goals into dependency-aware workstreams."),W("task-dispatcher","control","Dispatch ready jobs to eligible workers."),W("state-reconciler","control","Reconcile desired state against observed state."),W("release-coordinator","control","Move validated products through release gates.","medium","production_release"),W("evidence-collector","control","Collect and normalize proof for capability claims."),W("audit-worker","control","Create immutable audit records."),W("cost-optimizer","control","Identify waste and safe cost reductions."),W("incident-coordinator","control","Triage incidents and coordinate recovery.","medium","incident_action"),
W("identity-provisioner","identity","Create and maintain ecosystem identities.","medium","identity_change"),W("profile-worker","identity","Synchronize profiles."),W("consent-worker","identity","Record and enforce consent choices.","medium"),W("access-worker","identity","Evaluate access and entitlements."),W("credential-worker","identity","Rotate and validate service credentials.","high","credential_rotation"),
W("threat-detection-worker","security","Detect abuse, attacks and anomalies."),W("fraud-worker","security","Score suspicious transactions.","high","fraud_override"),W("vulnerability-worker","security","Discover application vulnerabilities."),W("security-response-worker","security","Coordinate bounded containment.","high","security_action"),W("privacy-worker","security","Detect privacy-policy violations.","high","privacy_exception"),
W("data-ingestion-worker","data","Ingest approved data."),W("data-quality-worker","data","Profile and repair data quality."),W("data-lineage-worker","data","Track origin and transformations."),W("knowledge-curator","data","Curate trusted knowledge."),W("backup-worker","data","Create and verify recoverable backups.","medium","restore"),
W("crawler-worker","search","Discover permitted content."),W("indexer-worker","search","Build searchable indexes."),W("ranking-worker","search","Rank results by relevance and trust."),W("search-quality-worker","search","Evaluate search quality."),
W("social-moderation-worker","social","Detect and route policy violations.","medium","moderation_override"),W("community-worker","social","Manage communities."),W("feed-worker","social","Assemble feeds."),W("notification-worker","social","Deliver notifications."),W("messaging-worker","social","Route messages and receipts."),
W("content-worker","media","Process media metadata and publishing."),W("transcode-worker","media","Create media derivatives."),W("rights-worker","media","Track rights and permissions.","high","rights_override"),W("creator-worker","media","Operate creator profiles and analytics."),W("recommendation-worker","media","Generate transparent recommendations."),
W("music-catalog-worker","music","Maintain music catalogs."),W("music-discovery-worker","music","Power music discovery."),W("royalty-worker","music","Calculate royalty allocations.","high","royalty_adjustment"),
W("catalog-worker","commerce","Maintain merchant catalogs."),W("merchant-worker","commerce","Onboard merchants.","medium","merchant_approval"),W("order-worker","commerce","Coordinate order lifecycle."),W("fulfilment-worker","commerce","Coordinate inventory and delivery."),W("returns-worker","commerce","Process returns and refunds.","high","refund"),W("marketplace-trust-worker","commerce","Detect unsafe or prohibited listings.","high","listing_override"),
W("payment-worker","finance","Create and reconcile payments.","high","payment_release"),W("ledger-worker","finance","Maintain double-entry records.","high","ledger_adjustment"),W("settlement-worker","finance","Prepare settlements.","high","settlement_release"),W("billing-worker","finance","Manage billing states."),W("reconciliation-worker","finance","Reconcile financial records.","high","reconciliation_override"),W("financial-risk-worker","finance","Monitor financial exposure.","high","risk_override"),
W("workspace-worker","work","Manage workspaces."),W("document-worker","work","Create and version documents."),W("meeting-worker","work","Coordinate meetings."),W("workflow-worker","work","Execute durable workflows."),W("crm-worker","work","Manage customer lifecycle."),
W("learner-worker","education","Manage learner journeys."),W("course-worker","education","Publish courses and assessments."),W("assessment-worker","education","Score assessments."),W("credentialing-worker","education","Issue education credentials.","medium","credential_issue"),
W("repo-worker","developer","Manage source repositories."),W("build-worker","developer","Build, test and package software."),W("code-review-worker","developer","Review changed code."),W("dependency-worker","developer","Track dependency risk."),W("deployment-worker","developer","Execute gated deployments.","high","production_deploy"),
W("provision-worker","cloud","Provision approved infrastructure.","high","infra_change"),W("dns-worker","cloud","Manage and verify DNS.","medium","dns_change"),W("ssl-worker","cloud","Provision and verify certificates."),W("observability-worker","cloud","Collect health signals."),W("recovery-worker","cloud","Execute tested recovery procedures.","high","recovery_action"),
W("market-research-worker","growth","Discover market opportunities."),W("campaign-worker","growth","Manage approved campaigns.","medium","paid_media"),W("creative-worker","growth","Generate marketing creative."),W("attribution-worker","growth","Measure acquisition and conversion."),W("seo-worker","growth","Run compliant SEO workflows.","medium","site_publish"),
W("support-triage-worker","support","Classify and route support issues."),W("support-resolution-worker","support","Resolve routine support cases.","medium","exception"),W("customer-success-worker","support","Identify retention interventions.","medium","customer_outreach"),
W("trust-worker","trust","Maintain trust signals."),W("dispute-worker","trust","Manage disputes and appeals.","high","case_decision"),W("verification-worker","trust","Verify people, organizations and claims.","high","verification_override"),
W("mobility-worker","mobility","Coordinate mobility supply and demand."),W("travel-worker","travel","Coordinate travel discovery and bookings.","high","booking_commit"),
W("model-router-worker","ai","Route AI jobs under policy."),W("agent-worker","ai","Run bounded multi-step agent tasks.","medium","high_impact_action"),W("evaluation-worker","ai","Evaluate models and agent outputs."),W("prompt-policy-worker","ai","Apply AI safety and privacy policy.","high","policy_override")
];
export const WORKER_INDEX=Object.fromEntries(WORKERS.map(w=>[w.id,w]));
