const API_BASE = window.IZAKHONO_SOCIAL_API || "https://yfawrenhudjomhnglfhq.supabase.co/functions/v1/connecta-external";
const TOKEN_KEY = "izakhono-social-session";
const state={account:null,token:sessionStorage.getItem(TOKEN_KEY)||"",activeView:"home",activeFeed:"for-you",search:"",posts:[],loading:false};
const feed=document.querySelector("#feed"),postTemplate=document.querySelector("#postTemplate"),composer=document.querySelector("#composer"),dynamicPanel=document.querySelector("#dynamicPanel"),postText=document.querySelector("#postText"),postButton=document.querySelector("#postButton"),charCount=document.querySelector("#charCount"),viewTitle=document.querySelector("#viewTitle"),viewSubtitle=document.querySelector("#viewSubtitle"),search=document.querySelector("#globalSearch"),dialog=document.querySelector("#postDialog"),dialogPostText=document.querySelector("#dialogPostText"),dialogPostButton=document.querySelector("#dialogPostButton"),dialogCharCount=document.querySelector("#dialogCharCount");

function apiUrl(action,params={}){const url=new URL(API_BASE);url.searchParams.set("action",action);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")url.searchParams.set(k,String(v))});return url.toString()}
async function api(action,options={},params={}){const headers={accept:"application/json",...(options.headers||{})};if(state.token)headers.authorization=`Bearer ${state.token}`;if(options.body&&typeof options.body!=="string"){headers["content-type"]="application/json";options={...options,body:JSON.stringify(options.body)}}const response=await fetch(apiUrl(action,params),{cache:"no-store",credentials:"omit",...options,headers});const data=await response.json().catch(()=>({ok:false,error:"Invalid server response"}));if(response.status===401&&!["login","register"].includes(action)){logoutLocal();showAuth("Your session expired. Please sign in again.")}return{response,data}}
function escapeHtml(text){return String(text??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function linkify(text){return text.replace(/(#[\p{L}\p{N}_-]+)/gu,'<a href="#" data-tag="$1">$1</a>').replace(/(@[\w.-]+)/g,'<a href="#" data-handle="$1">$1</a>').replace(/(https?:\/\/[^\s<]+)/g,'<a href="$1" target="_blank" rel="noopener">$1</a>')}
function initials(name){return String(name||"IS").split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()}
function compact(v){if(!v)return"";if(typeof v==="string")return v;if(v>=1e6)return(v/1e6).toFixed(1).replace(".0","")+"M";if(v>=1e3)return(v/1e3).toFixed(1).replace(".0","")+"K";return String(v)}
function relativeTime(v){if(!v)return"now";const d=Math.max(0,Date.now()-new Date(v).getTime()),m=Math.floor(d/60000);if(m<1)return"now";if(m<60)return m+"m";const h=Math.floor(m/60);return h<24?h+"h":Math.floor(h/24)+"d"}
function logoutLocal(){state.account=null;state.token="";state.posts=[];sessionStorage.removeItem(TOKEN_KEY)}
async function logout(){try{await api("logout",{method:"POST"})}catch{}logoutLocal();renderPosts();showAuth()}

function buildAuthGate(){
 const gate=document.createElement("div");gate.id="authGate";gate.className="auth-gate hidden";gate.innerHTML=`
 <section class="auth-panel">
   <div class="auth-brand"><span class="brand-mark">IS</span><div><strong>IZAKHONO SOCIAL</strong><small>Built in Africa. Open to the world.</small></div></div>
   <div class="auth-copy"><span class="eyebrow">FOUNDING NETWORK</span><h1>Your conversation.<br>Your community.<br>Your opportunity.</h1><p>Post, follow, reply, repost, save, message and build communities on an IZAKHONO-owned social platform.</p></div>
   <div class="auth-card">
     <div class="auth-tabs"><button type="button" class="active" data-auth-mode="register">Create account</button><button type="button" data-auth-mode="login">Sign in</button></div>
     <form id="authForm">
       <label class="register-only">Display name<input name="displayName" maxlength="100" required autocomplete="name"></label>
       <label class="register-only">Handle<input name="handle" maxlength="40" placeholder="your.handle" required autocomplete="username"></label>
       <label>Email<input name="email" type="email" required autocomplete="email"></label>
       <label>Password<input name="password" type="password" minlength="12" required autocomplete="current-password"></label>
       <button class="auth-submit" type="submit">Create account</button>
     </form>
     <p id="authMessage" class="auth-message"></p>
     <small class="auth-note">Passwords require at least 12 characters. The database service key never reaches this page.</small>
   </div>
 </section>`;document.body.appendChild(gate);
 let mode="register";const form=gate.querySelector("#authForm"),submit=gate.querySelector(".auth-submit"),message=gate.querySelector("#authMessage");
 gate.querySelectorAll("[data-auth-mode]").forEach(button=>button.addEventListener("click",()=>{mode=button.dataset.authMode;gate.querySelectorAll("[data-auth-mode]").forEach(b=>b.classList.toggle("active",b===button));gate.querySelectorAll(".register-only").forEach(el=>el.classList.toggle("hidden",mode==="login"));submit.textContent=mode==="login"?"Sign in":"Create account";form.querySelector('[name="displayName"]').required=mode==="register";form.querySelector('[name="handle"]').required=mode==="register";message.textContent=""}));
 form.addEventListener("submit",async event=>{event.preventDefault();submit.disabled=true;message.textContent="";const values=Object.fromEntries(new FormData(form).entries()),body={email:values.email,password:values.password};if(mode==="register"){body.displayName=values.displayName;body.handle=values.handle}try{const{response,data}=await api(mode,{method:"POST",body});if(!response.ok)throw new Error(data.error||"Could not continue");state.token=data.sessionToken||"";state.account=data.account;if(state.token)sessionStorage.setItem(TOKEN_KEY,state.token);hideAuth();hydrateAccountUI();await loadFeed()}catch(e){message.textContent=e.message||"Could not connect to IZAKHONO SOCIAL."}finally{submit.disabled=false}})
}
function showAuth(message=""){const gate=document.querySelector("#authGate");gate?.classList.remove("hidden");const msg=document.querySelector("#authMessage");if(msg&&message)msg.textContent=message}
function hideAuth(){document.querySelector("#authGate")?.classList.add("hidden")}
function hydrateAccountUI(){if(!state.account)return;const i=initials(state.account.display_name||state.account.handle);document.querySelectorAll(".avatar-owner").forEach(el=>el.textContent=i);const card=document.querySelector("#accountButton");if(card){const strong=card.querySelector("strong"),small=card.querySelector("small");if(strong)strong.textContent=state.account.display_name;if(small)small.textContent="@"+state.account.handle}}

function mapPost(post){const a=post.author||{};return{id:post.id,authorId:post.author_id,name:a.display_name||"IZAKHONO member",handle:"@"+(a.handle||"member"),initials:initials(a.display_name||a.handle),verified:!!a.verified,time:relativeTime(post.created_at),text:String(post.body||"").trim(),replies:post.metrics?.replies||0,reposts:post.metrics?.reposts||0,likes:post.metrics?.likes||0,views:"",parentPostId:post.parent_post_id||null,repostOfId:post.repost_of_id||null,quotePostId:post.quote_post_id||null,liked:!!post.viewer?.liked,bookmarked:!!post.viewer?.bookmarked}}
function renderPosts(){feed.innerHTML="";let posts=[...state.posts];if(state.search.trim()){const q=state.search.toLowerCase();posts=posts.filter(p=>[p.name,p.handle,p.text].join(" ").toLowerCase().includes(q))}if(!posts.length){feed.innerHTML=`<div class="panel-inner"><h2>${state.loading?"Loading…":"Your feed is ready for its first conversations"}</h2><p>${state.loading?"Connecting to the network.":"Follow people, create a post or switch feeds."}</p></div>`;return}posts.forEach(post=>{const node=postTemplate.content.cloneNode(true),article=node.querySelector(".post");article.dataset.id=post.id;const avatar=node.querySelector(".post-avatar");avatar.textContent=post.initials;node.querySelector(".post-name").textContent=post.name;node.querySelector(".post-handle").textContent=post.handle;node.querySelector(".post-time").textContent=post.time;node.querySelector(".post-text").innerHTML=linkify(escapeHtml(post.text||(post.repostOfId?"Reposted":"")));node.querySelector(".reply-count").textContent=compact(post.replies);node.querySelector(".repost-count").textContent=compact(post.reposts);node.querySelector(".like-count").textContent=compact(post.likes);node.querySelector(".view-count").textContent=compact(post.views);node.querySelector(".verified").classList.toggle("hidden",!post.verified);node.querySelector('[data-action="like"]').classList.toggle("active-like",post.liked);node.querySelector('[data-action="bookmark"]').classList.toggle("active-bookmark",post.bookmarked);feed.appendChild(node)})}
async function loadFeed(){if(!state.account)return;state.loading=true;renderPosts();try{const mode=state.activeFeed==="following"?"following":"for-you";const{response,data}=await api("social-feed",{}, {mode});if(!response.ok)throw new Error(data.error||"Could not load feed");state.posts=(data.posts||[]).map(mapPost)}catch(e){feed.innerHTML=`<div class="panel-inner"><h2>Network unavailable</h2><p>${escapeHtml(e.message)}</p></div>`;return}finally{state.loading=false}renderPosts()}
function updateComposer(){const n=postText.value.length;charCount.textContent=`${n} / 500`;postButton.disabled=n===0||n>500||!state.account}
async function publishPost(text,extra={}){const clean=String(text||"").trim();if(!clean&&!extra.repostOfId)return false;const{response,data}=await api("social-post",{method:"POST",body:{body:clean,...extra}});if(!response.ok){alert(data.error||"Could not publish post");return false}await loadFeed();return true}

postText.addEventListener("input",updateComposer);postButton.addEventListener("click",async()=>{postButton.disabled=true;const ok=await publishPost(postText.value);if(ok)postText.value="";updateComposer()});
feed.addEventListener("click",async event=>{
 const tag=event.target.closest("[data-tag]");if(tag){event.preventDefault();search.value=tag.dataset.tag;state.search=tag.dataset.tag;setView("explore");renderPosts();return}
 const h=event.target.closest("[data-handle]");if(h){event.preventDefault();await openProfile(h.dataset.handle.replace(/^@/,""));return}
 const button=event.target.closest("button[data-action]");if(!button)return;const post=state.posts.find(p=>p.id===button.closest(".post")?.dataset.id);if(!post)return;button.disabled=true;
 try{
  if(button.dataset.action==="like"){const{response,data}=await api("social-like-toggle",{method:"POST",body:{postId:post.id}});if(!response.ok)throw new Error(data.error);post.liked=data.liked;post.likes=Math.max(0,post.likes+(data.liked?1:-1))}
  if(button.dataset.action==="bookmark"){const{response,data}=await api("social-bookmark-toggle",{method:"POST",body:{postId:post.id}});if(!response.ok)throw new Error(data.error);post.bookmarked=data.bookmarked}
  if(button.dataset.action==="repost"){const{response,data}=await api("social-repost-toggle",{method:"POST",body:{postId:post.id}});if(!response.ok)throw new Error(data.error);post.reposts=Math.max(0,post.reposts+(data.reposted?1:-1))}
  if(button.dataset.action==="reply"){const reply=prompt(`Reply to ${post.handle}`);if(reply?.trim())await publishPost(reply.trim(),{parentPostId:post.id})}
  if(button.dataset.action==="share"){const shareText=`${post.name}: ${post.text}`;if(navigator.share)await navigator.share({title:"IZAKHONO SOCIAL",text:shareText}).catch(()=>{});else await navigator.clipboard?.writeText(shareText)}
  renderPosts()
 }catch(e){alert(e.message||"Action failed")}finally{button.disabled=false}
});
document.querySelectorAll(".feed-tab").forEach(button=>button.addEventListener("click",async()=>{state.activeFeed=button.dataset.feed;document.querySelectorAll(".feed-tab").forEach(b=>b.classList.toggle("active",b===button));await loadFeed()}));
document.querySelectorAll("[data-view]").forEach(button=>button.addEventListener("click",()=>setView(button.dataset.view)));document.querySelectorAll("[data-view-link]").forEach(button=>button.addEventListener("click",()=>setView(button.dataset.viewLink)));

async function setView(view){
 state.activeView=view;document.querySelectorAll("[data-view]").forEach(btn=>btn.classList.toggle("active",btn.dataset.view===view));
 const copy={home:["Home","What South Africa and the world are talking about."],explore:["Explore","Search people, topics, communities and opportunities."],communities:["Communities","Focused spaces for people with shared interests."],notifications:["Notifications","Mentions, follows, replies and network activity."],messages:["Messages","Private conversations and business enquiries."],bookmarks:["Bookmarks","Posts you saved for later."],business:["Business","Turn attention into leads, customers and opportunity."],profile:["Profile","Your public identity on IZAKHONO SOCIAL."]};[viewTitle.textContent,viewSubtitle.textContent]=copy[view]||copy.home;composer.classList.toggle("hidden",view!=="home");document.querySelector(".feed-tabs").classList.toggle("hidden",view!=="home");dynamicPanel.classList.add("hidden");
 if(view==="home"){feed.classList.remove("hidden");await loadFeed()}
 else if(view==="bookmarks"){feed.classList.remove("hidden");await loadBookmarks()}
 else if(view==="communities"){feed.innerHTML="";feed.classList.add("hidden");await loadCommunities()}
 else if(view==="notifications"){feed.innerHTML="";feed.classList.add("hidden");await loadNotifications()}
 else if(view==="messages"){feed.innerHTML="";feed.classList.add("hidden");await loadConversations()}
 else if(view==="profile"){feed.innerHTML="";feed.classList.add("hidden");await openProfile(state.account?.handle||"")}
 else if(view==="business"){feed.innerHTML="";feed.classList.add("hidden");dynamicPanel.innerHTML=businessPanel();dynamicPanel.classList.remove("hidden")}
 else{feed.classList.remove("hidden");dynamicPanel.innerHTML=explorePanel();dynamicPanel.classList.remove("hidden");renderPosts()}
 window.scrollTo({top:0,behavior:"smooth"})
}
async function loadBookmarks(){state.loading=true;renderPosts();const{response,data}=await api("social-bookmarks");state.loading=false;if(!response.ok){feed.innerHTML=`<div class="panel-inner"><h2>Could not load bookmarks</h2><p>${escapeHtml(data.error)}</p></div>`;return}state.posts=(data.posts||[]).map(mapPost);renderPosts()}
async function loadCommunities(){
 dynamicPanel.innerHTML='<div class="panel-inner"><h2>Communities</h2><p>Loading your spaces…</p></div>';dynamicPanel.classList.remove("hidden");const{response,data}=await api("communities");if(!response.ok){dynamicPanel.innerHTML=`<div class="panel-inner"><h2>Communities</h2><p>${escapeHtml(data.error)}</p></div>`;return}
 const cards=(data.communities||[]).map(c=>`<div class="mini-card"><strong>${escapeHtml(c.name)}</strong><p>${escapeHtml(c.description||"A community on IZAKHONO SOCIAL.")}</p><button data-community-id="${c.id}" ${c.joined?"disabled":""}>${c.joined?"Joined":"Join"}</button></div>`).join("");
 dynamicPanel.innerHTML=`<div class="panel-inner"><div class="panel-toolbar"><div><h2>Communities</h2><p>Join focused public spaces or start your own.</p></div><button id="createCommunity" class="panel-action">Create</button></div><div class="grid-cards">${cards||'<div class="mini-card"><strong>Start the first community</strong><p>Founding members can shape the network from day one.</p></div>'}</div></div>`;
 dynamicPanel.querySelector("#createCommunity")?.addEventListener("click",createCommunity);dynamicPanel.querySelectorAll("[data-community-id]").forEach(button=>button.addEventListener("click",async()=>{button.disabled=true;const{response,data}=await api("community-join",{method:"POST",body:{communityId:button.dataset.communityId}});if(!response.ok)alert(data.error||"Could not join");await loadCommunities()}))
}
async function createCommunity(){const name=prompt("Community name");if(!name?.trim())return;const description=prompt("What is this community for?")||"";const{response,data}=await api("community-create",{method:"POST",body:{name:name.trim(),description:description.trim()}});if(!response.ok)alert(data.error||"Could not create community");await loadCommunities()}
async function loadNotifications(){dynamicPanel.innerHTML='<div class="panel-inner"><h2>Notifications</h2><p>Loading activity…</p></div>';dynamicPanel.classList.remove("hidden");const{response,data}=await api("notifications"),rows=data.notifications||[];dynamicPanel.innerHTML=`<div class="panel-inner"><h2>Recent activity</h2><p>Follows, replies, safety and network updates.</p>${response.ok&&rows.length?rows.map(n=>`<div class="notification-row"><span class="avatar">${initials(n.kind)}</span><div><p><strong>${escapeHtml(n.title)}</strong><br>${escapeHtml(n.body)}</p><small>${relativeTime(n.created_at)}</small></div></div>`).join(""):'<div class="mini-card"><strong>No notifications yet</strong><p>Your activity will appear here.</p></div>'}</div>`}
async function loadConversations(){
 dynamicPanel.innerHTML='<div class="panel-inner"><h2>Messages</h2><p>Loading conversations…</p></div>';dynamicPanel.classList.remove("hidden");const{response,data}=await api("social-conversations"),rows=data.conversations||[];
 dynamicPanel.innerHTML=`<div class="panel-inner"><div class="panel-toolbar"><div><h2>Messages</h2><p>Private conversations and business enquiries.</p></div><button id="newConversation" class="panel-action">New message</button></div><div class="conversation-list">${response.ok&&rows.length?rows.map(c=>{const other=(c.members||[]).map(m=>m.account).find(a=>a&&a.id!==state.account.id);return`<button class="conversation-card" data-conversation-id="${c.id}"><span class="avatar">${initials(other?.display_name||"DM")}</span><span><strong>${escapeHtml(other?.display_name||c.title||"Conversation")}</strong><small>@${escapeHtml(other?.handle||"message")}</small></span><span>›</span></button>`}).join(""):'<div class="mini-card"><strong>No messages yet</strong><p>Start a private conversation with another member by handle.</p></div>'}</div></div>`;
 dynamicPanel.querySelector("#newConversation")?.addEventListener("click",startConversation);dynamicPanel.querySelectorAll("[data-conversation-id]").forEach(b=>b.addEventListener("click",()=>openConversation(b.dataset.conversationId)))
}
async function startConversation(){const h=prompt("Enter the member handle, for example @name");if(!h?.trim())return;const{response,data}=await api("social-conversation-create",{method:"POST",body:{handle:h.trim().replace(/^@/,"")}});if(!response.ok){alert(data.error||"Could not start conversation");return}await openConversation(data.conversation.id)}
async function openConversation(id){
 const{response,data}=await api("social-messages",{}, {conversationId:id});if(!response.ok){alert(data.error||"Could not load messages");return}
 dynamicPanel.innerHTML=`<div class="panel-inner"><div class="panel-toolbar"><button id="backMessages" class="panel-action secondary">← Back</button><h2>Conversation</h2></div><div class="message-thread">${(data.messages||[]).map(m=>`<div class="message-bubble ${m.sender_id===state.account.id?"mine":""}"><strong>${escapeHtml(m.sender?.display_name||"Member")}</strong><p>${escapeHtml(m.body)}</p><small>${relativeTime(m.created_at)}</small></div>`).join("")||'<p class="empty-copy">No messages yet.</p>'}</div><form id="messageForm" class="message-composer"><input name="body" maxlength="8000" placeholder="Write a message…" required><button class="post-button">Send</button></form></div>`;
 dynamicPanel.querySelector("#backMessages")?.addEventListener("click",loadConversations);dynamicPanel.querySelector("#messageForm")?.addEventListener("submit",async e=>{e.preventDefault();const input=e.currentTarget.elements.body,text=input.value.trim();if(!text)return;const{response,data}=await api("social-message-send",{method:"POST",body:{conversationId:id,body:text}});if(!response.ok)alert(data.error||"Could not send message");else await openConversation(id)})
}
async function openProfile(handleValue){
 const h=String(handleValue||"").replace(/^@/,"");dynamicPanel.innerHTML='<div class="panel-inner"><h2>Profile</h2><p>Loading profile…</p></div>';dynamicPanel.classList.remove("hidden");feed.classList.add("hidden");const{response,data}=await api("social-profile",{}, {handle:h});if(!response.ok){dynamicPanel.innerHTML=`<div class="panel-inner"><h2>Profile unavailable</h2><p>${escapeHtml(data.error)}</p></div>`;return}
 const p=data.profile;dynamicPanel.innerHTML=`<div class="panel-inner"><div class="profile-hero"><div class="profile-cover"></div><div class="profile-info"><span class="avatar avatar-owner">${initials(p.display_name)}</span><div class="profile-title-row"><div><h2>${escapeHtml(p.display_name)} ${p.verified?"✓":""}</h2><div class="handle">@${escapeHtml(p.handle)}</div></div>${p.id!==state.account.id?`<button id="followProfile" class="follow-button ${data.isFollowing?"following":""}">${data.isFollowing?"Following":"Follow"}</button>`:'<button id="logoutButton" class="follow-button following">Sign out</button>'}</div><p>${escapeHtml(p.bio||"Member of IZAKHONO SOCIAL.")}</p><div class="profile-stats"><span><b>${compact(data.following)}</b> Following</span><span><b>${compact(data.followers)}</b> Followers</span></div></div></div></div>`;
 dynamicPanel.querySelector("#followProfile")?.addEventListener("click",async()=>{const{response,data:r}=await api("social-follow-toggle",{method:"POST",body:{handle:p.handle}});if(!response.ok)alert(r.error||"Could not follow");else await openProfile(p.handle)});dynamicPanel.querySelector("#logoutButton")?.addEventListener("click",logout)
}
function explorePanel(){return`<div class="panel-inner"><h2>Discover the network</h2><p>Search the feed or explore communities built around useful conversations.</p><div class="grid-cards"><div class="mini-card"><strong>#BuildInAfrica</strong><p>Manufacturing, startups, infrastructure and African-made products.</p><button data-search="#BuildInAfrica">Open topic</button></div><div class="mini-card"><strong>Creators & Music</strong><p>New releases, live events, rights, collaboration and fan communities.</p><button data-search="music">Explore</button></div><div class="mini-card"><strong>Jobs & Skills</strong><p>Employment, training, apprenticeships and verified opportunities.</p><button data-search="skills">Explore</button></div><div class="mini-card"><strong>SME Growth</strong><p>Sales, payments, funding, websites and practical business tools.</p><button data-search="business">Explore</button></div></div></div>`}
function businessPanel(){return`<div class="panel-inner"><h2>Business Centre</h2><p>Convert audience into measurable outcomes without changing the core social experience.</p><div class="grid-cards"><div class="mini-card"><strong>Business profile</strong><p>Add products, services, links and approved contact routes.</p><button>Configure</button></div><div class="mini-card"><strong>Promote a post</strong><p>Campaign controls will connect to IZAKHONO’s advertising engine after commercial review.</p><button disabled>Planned</button></div><div class="mini-card"><strong>Lead inbox</strong><p>Route enquiries into IZAKHONO customer workflows.</p><button>Open leads</button></div><div class="mini-card"><strong>Commerce</strong><p>Connect approved payment links when product, legal and reconciliation gates are ready.</p><button disabled>Controlled</button></div></div></div>`}
search?.addEventListener("input",()=>{state.search=search.value;if(state.activeView!=="explore")setView("explore");renderPosts()});dynamicPanel.addEventListener("click",e=>{const b=e.target.closest("[data-search]");if(!b)return;search.value=b.dataset.search;state.search=b.dataset.search;renderPosts()});
document.querySelector("#joinCommunityButton").addEventListener("click",()=>setView("communities"));document.querySelector("#sidebarPost").addEventListener("click",()=>{setView("home");postText.focus()});document.querySelector("#openComposer").addEventListener("click",()=>dialog.showModal());document.querySelector("#accountButton")?.addEventListener("click",()=>setView("profile"));
dialogPostText.addEventListener("input",()=>{dialogCharCount.textContent=`${dialogPostText.value.length} / 500`});dialogPostButton.addEventListener("click",async e=>{if(!dialogPostText.value.trim()){e.preventDefault();return}e.preventDefault();const ok=await publishPost(dialogPostText.value);if(ok){dialogPostText.value="";dialogCharCount.textContent="0 / 500";dialog.close()}});
async function boot(){buildAuthGate();updateComposer();if(!state.token){renderPosts();showAuth();return}try{const{response,data}=await api("social-me");if(!response.ok)throw new Error(data.error||"Session unavailable");state.account=data.account;hydrateAccountUI();hideAuth();await loadFeed()}catch{logoutLocal();showAuth("Please sign in to continue.")}}
boot();