options {
  directory "/var/cache/bind";
  listen-on { any; };
  listen-on-v6 { any; };
  recursion no;
  allow-query { any; };
  allow-query-cache { none; };
  version "IZAKHONO DNS";
};

include "/etc/bind/keys/izakhono-controller.key";

zone "izakhonoafrica.co.za" IN {
  type primary;
  file "/var/lib/bind/izakhonoafrica.co.za.zone";
  notify yes;
  allow-transfer { 172.30.0.11; };
  also-notify { 172.30.0.11; };
  update-policy {
    grant izakhono-controller zonesub ANY;
  };
};
