const app=document.querySelector("#root");
let mode="drive"; let safety=true; let emergency=false;
function render(){
const guardianState=safety?"Monitoring journey conditions":"Monitoring paused";
app.innerHTML='<div class="shell"><header><div class="brand"><span class="mark">I</span><div><b>IZAKHONO NAV</b><small>SAFETY INFRASTRUCTURE</small></div></div><div class="status"><i></i> SAFE MODE ON</div></header><main><section class="map"><div class="mapgrid"></div><div class="road r1"></div><div class="road r2"></div><div class="road r3"></div><div class="route"></div><div class="vehicle">▲</div><div class="destination"><span>●</span><div><b>Destination</b><small>Johannesburg CBD</small></div></div><div class="turn"><strong>350 m</strong><span>Keep left</span></div></section><section class="control"><div class="trip"><div><small>ARRIVAL</small><b>14:18</b></div><div><small>ETA</small><b>23 min</b></div><div><small>ROUTE</small><b>18.4 km</b></div></div><div class="guardian '+(safety?"active":"")+'"><span>🛡️</span><div><b>Driver Safety Guardian</b><small>'+guardianState+'</small></div><button id="guardian">'+(safety?"ON":"OFF")+'</button></div><div class="actions"><button id="safe" class="action">🛡️<span>Safety</span></button><button id="voice" class="action">🎙️<span>Companion</span></button><button id="fleet" class="action">🚗<span>Vehicle</span></button><button id="help" class="action danger">🚨<span>Emergency</span></button></div><div class="panel"><div><small>JOURNEY INTELLIGENCE</small><b>Road risk: LOW</b></div><div><small>CONNECTIVITY</small><b>Offline-ready</b></div><div><small>FORTRESS</small><b>Protected</b></div></div></section></main><footer><button class="'+(mode==="drive"?"selected":"")+'" data-mode="drive">🗺️<span>Navigate</span></button><button class="'+(mode==="safety"?"selected":"")+'" data-mode="safety">🛡️<span>Safety</span></button><button class="'+(mode==="fleet"?"selected":"")+'" data-mode="fleet">🏢<span>Fleet</span></button><button>⚙️<span>More</span></button></footer>'+(emergency?'<div class="overlay"><div class="modal"><div class="alert">🚨</div><h2>Emergency Response</h2><p>Choose the safest response. No call or alert is sent until you confirm.</p><button id="confirm" class="confirm">CONFIRM EMERGENCY</button><button id="cancel" class="cancel">CANCEL</button></div></div>':"")+'</div>';
document.querySelector("#guardian")?.addEventListener("click",()=>{safety=!safety;render()});
document.querySelector("#help")?.addEventListener("click",()=>{emergency=true;render()});
document.querySelector("#cancel")?.addEventListener("click",()=>{emergency=false;render()});
document.querySelector("#confirm")?.addEventListener("click",()=>{alert("Emergency workflow staged. Production integration will connect verified emergency contacts and FORTRESS.");emergency=false;render()});
document.querySelectorAll("[data-mode]").forEach(x=>x.addEventListener("click",()=>{mode=x.dataset.mode;render()}));
}
render();