import {createServer} from 'node:http';
import {createHash,randomBytes,randomUUID} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
const execFileAsync=promisify(execFile);
const port=Number(process.env.COMMANDER_PORT||8787),admin=process.env.COMMANDER_ADMIN_SECRET;
if(!admin||admin.length<24)throw new Error('COMMANDER_ADMIN_SECRET must be at least 24 characters');
type Device={id:string,name:string,platform:string,status:string,agentTokenHash:string,enrolledAt:string,lastSeenAt:string,createdAt:string};
const devices=new Map<string,Device>(),pairings=new Map<string,{deviceId:string,expires:number,used:boolean}>(),audit:Record<string,unknown>[]=[];
const hash=(x:string)=>createHash('sha256').update(x).digest('hex'),now=()=>new Date().toISOString();
const send=(res:any,status:number,data:unknown,type='application/json')=>{res.writeHead(status,{'content-type':type,'cache-control':'no-store'});res.end(type==='application/json'?JSON.stringify(data):String(data))};
const body=async(req:any)=>{let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}};
const log=(actor:string,action:string,target:string,outcome:string,detail='')=>audit.push({actor,action,target,outcome,detail,createdAt:now()});
const adminOk=(req:any)=>req.headers['x-commander-admin']===admin;
const agentOk=(req:any,d:Device)=>{const h=String(req.headers.authorization||'');const t=h.replace(/^Bearer /i,'');return !!t&&hash(t)===d.agentTokenHash};
const commands:Record<string,{file:string,args:string[]}>= {hostname:{file:'hostname',args:[]},node_version:{file:process.execPath,args:['--version']},platform:{file:process.platform==='win32'?'powershell':'uname',args:process.platform==='win32'?['-NoProfile','-Command','$PSVersionTable.Platform']:['-a']}};
const html='<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IZAKHONO COMMANDER</title><style>body{font:16px system-ui;background:#07130f;color:#edf7f1;max-width:1000px;margin:auto;padding:28px}.card{background:#10231b;border:1px solid #214334;border-radius:14px;padding:18px;margin:12px 0}button,input{padding:10px;border-radius:8px;margin:4px}pre{white-space:pre-wrap}</style></head><body><h1>IZAKHONO COMMANDER</h1><p>Owned-first remote control plane</p><div class="card"><input id="s" type="password" placeholder="Admin secret"><button onclick="unlock()">Unlock</button></div><div class="card"><button onclick="pair()">Generate pairing code</button><pre id="p">-</pre></div><div class="card"><button onclick="load()">Refresh devices</button><pre id="d">-</pre></div><script>let s=sessionStorage.getItem('cs')||'';async function api(p,o={}){o.headers={...(o.headers||{}),'x-commander-admin':s};let r=await fetch(p,o),x=await r.json();if(!r.ok)throw Error(x.error);return x}function unlock(){s=document.getElementById('s').value;sessionStorage.setItem('cs',s);load()}async function pair(){document.getElementById('p').textContent=JSON.stringify(await api('/api/pairings',{method:'POST'}),null,2)}async function load(){document.getElementById('d').textContent=JSON.stringify(await api('/api/devices'),null,2)}</script></body></html>';
createServer(async(req,res)=>{try{const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`),p=u.pathname;
if(req.method==='GET'&&p==='/'){send(res,200,html,'text/html');return}if(req.method==='GET'&&p==='/api/health'){send(res,200,{ok:true,service:'izakhono-commander',version:'0.1.0',time:now()});return}
if(p.startsWith('/api/')&&!p.startsWith('/api/agent/')&&!adminOk(req)){send(res,401,{error:'unauthorized'});return}
if(req.method==='GET'&&p==='/api/devices'){send(res,200,[...devices.values()].map(d=>({...d,agentTokenHash:undefined})));return}
if(req.method==='POST'&&p==='/api/pairings'){const deviceId='dev_'+randomUUID(),code=randomBytes(4).toString('hex').toUpperCase();pairings.set(hash(code),{deviceId,expires:Date.now()+600000,used:false});log('operator','pair.create',deviceId,'ok');send(res,200,{deviceId,pairingCode:code,expiresInSeconds:600});return}
if(req.method==='GET'&&p==='/api/audit'){send(res,200,audit.slice(-200).reverse());return}
if(req.method==='POST'&&p==='/api/agent/enroll'){const b=await body(req),pair=pairings.get(hash(String(b.pairingCode||'')));if(!pair||pair.used||pair.expires<Date.now()){send(res,403,{error:'invalid_or_expired_pairing'});return}pair.used=true;const agentToken=randomBytes(32).toString('hex'),d:Device={id:pair.deviceId,name:String(b.name||pair.deviceId),platform:String(b.platform||'unknown'),status:'online',agentTokenHash:hash(agentToken),enrolledAt:now(),lastSeenAt:now(),createdAt:now()};devices.set(d.id,d);log(d.id,'agent.enroll',d.id,'ok');send(res,200,{deviceId:d.id,agentToken});return}
if(req.method==='POST'&&p==='/api/agent/heartbeat'){const b=await body(req),d=devices.get(String(b.deviceId));if(!d||!agentOk(req,d)){send(res,401,{error:'unauthorized'});return}d.lastSeenAt=now();d.status='online';send(res,200,{ok:true,time:d.lastSeenAt});return}
if(req.method==='POST'&&p==='/api/agent/command'){const b=await body(req),d=devices.get(String(b.deviceId));if(!d||!agentOk(req,d)){send(res,401,{error:'unauthorized'});return}const spec=commands[String(b.command)];if(!spec){send(res,403,{error:'command_not_allowed'});return}try{const o=await execFileAsync(spec.file,spec.args,{timeout:10000,maxBuffer:1048576});log(d.id,'command',String(b.command),'ok');send(res,200,{ok:true,stdout:o.stdout,stderr:o.stderr})}catch(e){log(d.id,'command',String(b.command),'error',String(e));send(res,500,{error:'command_failed'})}return}
send(res,404,{error:'not_found'});}catch(e){send(res,500,{error:'internal_error'})}}).listen(port,()=>console.log('IZAKHONO COMMANDER listening on '+port));
