import {createServer,IncomingMessage,ServerResponse} from 'node:http';
import {createHash,randomBytes,randomUUID} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {WebSocketServer,WebSocket} from 'ws';
const execFileAsync=promisify(execFile);
const port=Number(process.env.COMMANDER_PORT||8787),admin=process.env.COMMANDER_ADMIN_SECRET;
if(!admin||admin.length<24)throw new Error('COMMANDER_ADMIN_SECRET must be at least 24 characters');
type Device={id:string,name:string,platform:string,status:string,agentTokenHash:string,enrolledAt:string,lastSeenAt:string,createdAt:string};
type GraphicsSession={id:string,deviceId:string,operatorId:string,token:string,expiresAt:string,state:'active'|'closed'};
const devices=new Map<string,Device>(),pairings=new Map<string,{deviceId:string,expires:number,used:boolean}>(),audit:Record<string,unknown>[]=[];
const sessions=new Map<string,GraphicsSession>(),operatorSockets=new Map<string,WebSocket>(),inputQueues=new Map<string,unknown[]>();
const hash=(x:string)=>createHash('sha256').update(x).digest('hex'),now=()=>new Date().toISOString();
const send=(res:ServerResponse,status:number,data:unknown,type='application/json')=>{res.writeHead(status,{'content-type':type,'cache-control':'no-store'});res.end(type==='application/json'?JSON.stringify(data):String(data))};
const body=async(req:IncomingMessage)=>{let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}};
const log=(actor:string,action:string,target:string,outcome:string,detail='')=>audit.push({actor,action,target,outcome,detail,createdAt:now()});
const adminOk=(req:IncomingMessage)=>req.headers['x-commander-admin']===admin;
const agentOk=(req:IncomingMessage,d:Device)=>{const h=String(req.headers.authorization||'');const t=h.replace(/^Bearer /i,'');return !!t&&hash(t)===d.agentTokenHash};
const commands:Record<string,{file:string,args:string[]}>= {hostname:{file:'hostname',args:[]},node_version:{file:process.execPath,args:['--version']},platform:{file:process.platform==='win32'?'powershell':'uname',args:process.platform==='win32'?['-NoProfile','-Command','$PSVersionTable.Platform']:['-a']}};
const graphicsHtml='<!doctype html><html><body style="margin:0;background:#050b08;color:#edf7f1;font:14px system-ui"><div style="height:52px;padding:10px;box-sizing:border-box"><input id="device" placeholder="Device ID"><button id="connect">Connect</button><button id="stop">Stop</button><span id="state">Disconnected</span></div><img id="screen" style="width:100vw;height:calc(100vh - 52px);object-fit:contain;background:#000"><script>const i=document.getElementById("screen"),s=document.getElementById("state");let w=null;const st=x=>s.textContent=x;async function c(){const d=document.getElementById("device").value.trim();if(!d)return st("Enter device ID");st("Authorizing...");const r=await fetch("/api/graphics/session",{method:"POST",headers:{"x-commander-admin":sessionStorage.getItem("cs")||"","content-type":"application/json"},body:JSON.stringify({deviceId:d})});if(!r.ok)return st("Authorization failed");const x=await r.json();w=new WebSocket(x.websocketUrl);w.onopen=()=>st("Connected");w.onclose=()=>st("Disconnected");w.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==="frame")i.src="data:image/jpeg;base64,"+m.data;if(m.type==="ready")st("Remote desktop active")};}function send(e){if(w&&w.readyState===1)w.send(JSON.stringify({type:"input",event:e}))}i.onpointermove=e=>send({type:"pointer_move",x:e.offsetX/i.clientWidth*i.naturalWidth,y:e.offsetY/i.clientHeight*i.naturalHeight});i.onpointerdown=e=>{e.preventDefault();send({type:"mouse_button",button:e.button===2?"right":e.button===1?"middle":"left",down:true})};i.onpointerup=e=>{e.preventDefault();send({type:"mouse_button",button:e.button===2?"right":e.button===1?"middle":"left",down:false})};i.onwheel=e=>{e.preventDefault();send({type:"wheel",deltaX:e.deltaX,deltaY:e.deltaY})};i.oncontextmenu=e=>e.preventDefault();onkeydown=e=>send({type:"key",code:e.code,down:true});onkeyup=e=>send({type:"key",code:e.code,down:false});document.getElementById("connect").onclick=c;document.getElementById("stop").onclick=()=>{w&&w.close();st("Stopped")};</script></body></html>';
const server=createServer(async(req,res)=>{try{const u=new URL(req.url||'/', 'http://'+(req.headers.host||'localhost')),p=u.pathname;
if(req.method==='GET'&&p==='/'){send(res,200,'<h1>IZAKHONO COMMANDER</h1><p><a href="/graphics">Open Remote Desktop</a></p>','text/html');return}
if(req.method==='GET'&&p==='/graphics'){send(res,200,graphicsHtml,'text/html');return}
if(req.method==='GET'&&p==='/api/health'){send(res,200,{ok:true,service:'izakhono-commander',version:'0.2.0-graphics',time:now()});return}
if(p.startsWith('/api/')&&!p.startsWith('/api/agent/')&&!adminOk(req)){send(res,401,{error:'unauthorized'});return}
if(req.method==='GET'&&p==='/api/devices'){send(res,200,[...devices.values()].map(d=>({...d,agentTokenHash:undefined,graphicsOnline:[...sessions.values()].some(s=>s.deviceId===d.id&&s.state==='active')})));return}
if(req.method==='POST'&&p==='/api/pairings'){const deviceId='dev_'+randomUUID(),code=randomBytes(4).toString('hex').toUpperCase();pairings.set(hash(code),{deviceId,expires:Date.now()+600000,used:false});log('operator','pair.create',deviceId,'ok');send(res,200,{deviceId,pairingCode:code,expiresInSeconds:600});return}
if(req.method==='GET'&&p==='/api/audit'){send(res,200,audit.slice(-200).reverse());return}
if(req.method==='POST'&&p==='/api/agent/enroll'){const b=await body(req),pair=pairings.get(hash(String(b.pairingCode||'')));if(!pair||pair.used||pair.expires<Date.now()){send(res,403,{error:'invalid_or_expired_pairing'});return}pair.used=true;const agentToken=randomBytes(32).toString('hex'),d:Device={id:pair.deviceId,name:String(b.name||pair.deviceId),platform:String(b.platform||'unknown'),status:'online',agentTokenHash:hash(agentToken),enrolledAt:now(),lastSeenAt:now(),createdAt:now()};devices.set(d.id,d);log(d.id,'agent.enroll',d.id,'ok');send(res,200,{deviceId:d.id,agentToken});return}
if(req.method==='POST'&&p==='/api/agent/heartbeat'){const b=await body(req),d=devices.get(String(b.deviceId));if(!d||!agentOk(req,d)){send(res,401,{error:'unauthorized'});return}d.lastSeenAt=now();d.status='online';send(res,200,{ok:true,time:d.lastSeenAt});return}
if(req.method==='POST'&&p==='/api/agent/command'){const b=await body(req),d=devices.get(String(b.deviceId));if(!d||!agentOk(req,d)){send(res,401,{error:'unauthorized'});return}const spec=commands[String(b.command)];if(!spec){send(res,403,{error:'command_not_allowed'});return}try{const o=await execFileAsync(spec.file,spec.args,{timeout:10000,maxBuffer:1048576});log(d.id,'command',String(b.command),'ok');send(res,200,{ok:true,stdout:o.stdout,stderr:o.stderr})}catch(e){log(d.id,'command',String(b.command),'error',String(e));send(res,500,{error:'command_failed'})}return}
if(req.method==='POST'&&p==='/api/graphics/session'){const b=await body(req),d=devices.get(String(b.deviceId));if(!d){send(res,404,{error:'device_not_found'});return}for(const s of sessions.values())if(s.deviceId===d.id&&s.state==='active')s.state='closed';const id='gfx_'+randomUUID(),token=randomBytes(32).toString('hex'),expiresAt=new Date(Date.now()+900000).toISOString();sessions.set(id,{id,deviceId:d.id,operatorId:'operator',token,expiresAt,state:'active'});inputQueues.set(id,[]);log('operator','graphics.session.start',d.id,'ok',id);send(res,200,{sessionId:id,expiresAt,websocketUrl:(u.protocol==='https:'?'wss':'ws')+'://'+u.host+'/api/graphics/ws?session='+encodeURIComponent(id)+'&token='+encodeURIComponent(token)});return}
if(req.method==='POST'&&p==='/api/graphics/stop'){const b=await body(req),s=sessions.get(String(b.sessionId));if(!s){send(res,404,{error:'session_not_found'});return}s.state='closed';operatorSockets.get(s.id)?.close();log('operator','graphics.session.stop',s.deviceId,'ok',s.id);send(res,200,{ok:true});return}
if(req.method==='POST'&&p==='/api/agent/graphics/frame'){const b=await body(req),d=devices.get(String(b.deviceId));if(!d||!agentOk(req,d)){send(res,401,{error:'unauthorized'});return}const s=sessions.get(String(b.sessionId));if(!s||s.deviceId!==d.id||s.state!=='active'||Date.parse(s.expiresAt)<Date.now()){send(res,409,{error:'graphics_session_inactive'});return}if(typeof b.data!=='string'||b.data.length>8000000){send(res,413,{error:'frame_too_large'});return}const ws=operatorSockets.get(s.id);if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'frame',data:b.data}));send(res,200,{ok:true});return}
if(req.method==='POST'&&p==='/api/agent/graphics/poll'){const b=await body(req),d=devices.get(String(b.deviceId));if(!d||!agentOk(req,d)){send(res,401,{error:'unauthorized'});return}const s=[...sessions.values()].find(x=>x.deviceId===d.id&&x.state==='active'&&Date.parse(x.expiresAt)>Date.now());if(!s){send(res,200,{active:false,events:[]});return}d.lastSeenAt=now();const q=inputQueues.get(s.id)||[];inputQueues.set(s.id,[]);send(res,200,{active:true,sessionId:s.id,events:q});return}
send(res,404,{error:'not_found'});}catch(e){send(res,500,{error:'internal_error'})}});
const wss=new WebSocketServer({noServer:true,perMessageDeflate:false});
server.on('upgrade',(req,socket,head)=>{try{const u=new URL(req.url||'/', 'http://'+(req.headers.host||'localhost'));if(u.pathname!=='/api/graphics/ws'){socket.destroy();return}const s=sessions.get(String(u.searchParams.get('session')||'')),t=String(u.searchParams.get('token')||'');if(!s||s.token!==t||s.state!=='active'||Date.parse(s.expiresAt)<Date.now()){socket.destroy();return}wss.handleUpgrade(req,socket,head,ws=>{operatorSockets.set(s.id,ws);ws.send(JSON.stringify({type:'ready',expiresAt:s.expiresAt}));ws.on('message',raw=>{try{const m=JSON.parse(raw.toString());if(m.type==='input'){const q=inputQueues.get(s.id)||[];if(q.length<200)q.push(m.event);inputQueues.set(s.id,q);log('operator','graphics.input',s.deviceId,'queued',String(m.event?.type||'unknown'))}if(m.type==='close'){s.state='closed';ws.close()}}catch{}});ws.on('close',()=>{if(operatorSockets.get(s.id)===ws)operatorSockets.delete(s.id)})});}catch{socket.destroy()}});
server.listen(port,()=>console.log('IZAKHONO COMMANDER listening on '+port));