services:
  dns-primary:
    image: internetsystemsconsortium/bind9:9.20
    container_name: izakhono-dns-primary
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./bind/primary/named.conf:/etc/bind/named.conf:ro
      - ./bind/primary/zones:/var/lib/bind
      - ./bind/primary/keys:/etc/bind/keys:ro
    networks:
      dns:
        ipv4_address: 172.30.0.10

  dns-secondary:
    image: internetsystemsconsortium/bind9:9.20
    container_name: izakhono-dns-secondary
    restart: unless-stopped
    volumes:
      - ./bind/secondary/named.conf:/etc/bind/named.conf:ro
      - ./bind/secondary/zones:/var/lib/bind
    networks:
      dns:
        ipv4_address: 172.30.0.11
    depends_on:
      - dns-primary

  dns-api:
    build: ./controller
    container_name: izakhono-dns-controller
    restart: unless-stopped
    environment:
      DNS_PRIMARY_HOST: 172.30.0.10
      DNS_PRIMARY_PORT: "53"
      DNS_API_KEY: change-me-before-production
    ports:
      - "8088:8080"
    volumes:
      - ./bind/primary/keys:/secrets:ro
    networks:
      dns:
        ipv4_address: 172.30.0.20
    depends_on:
      - dns-primary

networks:
  dns:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
