import http from "node:http";
import fs from "node:fs/promises";
import path from "node:path";
import dns from "node:dns/promises";
import net from "node:net";
import { fileURLToPath } from "node:url";
import { providerStatus, searchBatch } from "./search-provider.mjs";

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT||8097); const PUBLIC=path.join(__dirname,"public"); const now=()=>new Date().toISOString();
const clean=(v,n=500)=>String(v??"").trim().replace(/[\u0000-\u001f\u007f]/g," ").slice(0,n);
const esc=v=>String(v??"").replace(/[&<>\"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[s]));
const stop=new Set("the a an and or for to of in on with from your our how what why best top guide near south africa sa is are be by into vs versus 2026 2025".split(" "));
function words(s){return [...new Set(clean(s,5000).toLowerCase().replace(/[^a-z0-9 -]/g," ").split(/\s+/).filter(x=>x.length>2&&!stop.has(x)))];}
function slug(s){return clean(s,160).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
function scoreKeyword(k,i){const intent=/price|cost|quote|supplier|buy|service|company|provider|course|training|hosting|email|repair/i.test(k)?"commercial":/how|what|guide|tips|requirements|learn/i.test(k)?"informational":"discovery";const longTail=k.split(" ").length>=3;return {keyword:k,intent,long_tail:longTail,difficulty:Math.min(95,25+i*4+(longTail?-8:8)),opportunity:Math.max(20,92-i*5+(longTail?12:0)),priority:Math.max(1,Math.round((92-i*5+(longTail?12:0))/10))};}
function clusterKeywords(seed){const base=[...new Set(seed.flatMap(words))];const phrases=[];for(const k of base)phrases.push(k,`${k} south africa`,`best ${k}`,`${k} price`,`${k} services`,`how to ${k}`);return [...new Set(phrases)].filter(x=>x.split(" ").length<=7).slice(0,60).map(scoreKeyword);}
function makePlan(keywords,domain){const chosen=keywords.slice().sort((a,b)=>b.opportunity-a.opportunity).slice(0,18);return chosen.map((x,i)=>({id:`seo-${i+1}`,title:`${x.keyword.replace(/\b\w/g,c=>c.toUpperCase())}: A Practical Guide`,keyword:x.keyword,intent:x.intent,word_count:x.intent==="commercial"?1300:1500,difficulty:x.difficulty,opportunity:x.opportunity,cta:x.intent==="commercial"?"Request a quote / start now":"Explore the related service or guide",target_url:`https://${domain}/insights/${slug(x.keyword)}`,internal_links:[`https://${domain}/`,...chosen.slice(Math.max(0,i-2),i).map(y=>`https://${domain}/insights/${slug(y.keyword)}`)]}));}
function analyze(input){const domain=clean(input.domain,180).replace(/^https?:\/\//,"").replace(/\/.*/,"");const competitors=(Array.isArray(input.competitors)?input.competitors:[]).map(x=>clean(x,180).replace(/^https?:\/\//,"").replace(/\/.*/,"")).filter(Boolean).slice(0,10);const seed=(Array.isArray(input.seed_keywords)?input.seed_keywords:[]).map(x=>clean(x,120)).filter(Boolean).slice(0,20);if(!domain)throw new Error("domain is required");if(!seed.length)throw new Error("at least one seed keyword is required");const keywords=clusterKeywords(seed);const plan=makePlan(keywords,domain);const gaps=keywords.filter(x=>x.long_tail||x.intent==="commercial").slice(0,24).map((x,i)=>({keyword:x.keyword,opportunity:x.opportunity,why:i<8?"High-intent or long-tail opportunity":"Supporting topic opportunity",competitors_missing:competitors.slice(0,3)}));const pages=(Array.isArray(input.pages)?input.pages:[]).map(x=>clean(x,300)).filter(Boolean).slice(0,30);const internal=plan.slice(0,12).map((p,i)=>({source:p.target_url,target:pages[i%Math.max(1,pages.length)]||`https://${domain}/`,reason:"topic-cluster relevance",anchor:p.keyword}));const authority=competitors.map(c=>({domain:c,type:"research target",angle:"Find genuine editorial/resource/partner opportunities; do not exchange or automate links.",priority:"medium"}));return {schema:"izakhono.super-seo.analysis.v1",generated_at:now(),domain,competitors,seed_keywords:seed,summary:{keywords_found:keywords.length,content_opportunities:plan.length,gaps:gaps.length,authority_targets:authority.length},keywords,content_plan:plan,gaps,internal_link_map:internal,authority_opportunities:authority,guardrails:["No automated backlink exchange.","No paid ranking links; qualifying sponsored links must use appropriate rel attributes.","No mass low-value AI pages.","Every generated page requires human/product-value review before publication."],next_actions:["review_top_10_keywords","approve_first_content_cluster","publish_or_schedule","measure_search_and_leads"]};}

function normalizeDomain(value){return clean(value,180).replace(/^https?:\/\//,"").replace(/\/.*/,"").toLowerCase();}
function buildSearchOpportunities(domain, competitors, searchResults){const owned=normalizeDomain(domain);const comp=new Set(competitors.map(normalizeDomain));return searchResults.map((item)=>{const rows=item.results||[];const ownedPositions=rows.filter(r=>normalizeDomain(r.domain||r.url)===owned).map(r=>r.position);const competitorRows=rows.filter(r=>comp.has(normalizeDomain(r.domain||r.url)));const competitorDomains=[...new Set(competitorRows.map(r=>normalizeDomain(r.domain||r.url)).filter(Boolean))];const bestOwned=ownedPositions.length?Math.min(...ownedPositions):null;const intent=/price|cost|quote|supplier|buy|service|company|provider|course|training|hosting|email|repair/i.test(item.query)?"commercial":/how|what|guide|tips|requirements|learn/i.test(item.query)?"informational":"discovery";const longTail=item.query.trim().split(/\s+/).length>=3;let score=20;if(bestOwned===null)score+=30;if(competitorRows.length)score+=20;if(longTail)score+=15;if(intent==="commercial")score+=15;if(item.metrics?.search_volume)score+=Math.min(10,item.metrics.search_volume>1000?10:item.metrics.search_volume>100?6:2);return {query:item.query,opportunity:Math.min(100,score),intent,long_tail:longTail,owned_position:bestOwned,competitor_domains:competitorDomains,competitor_gap:bestOwned===null&&competitorRows.length>0,data_source:item.source||"provider",...(item.metrics?{metrics:item.metrics}:{})};});}
async function searchIntelligence(input){const domain=normalizeDomain(input.domain);if(!domain)throw new Error("domain is required");const seeds=(Array.isArray(input.seed_keywords)?input.seed_keywords:[]).map(x=>clean(x,120)).filter(Boolean).slice(0,20);if(!seeds.length)throw new Error("at least one seed keyword is required");const competitors=(Array.isArray(input.competitors)?input.competitors:[]).map(normalizeDomain).filter(Boolean).slice(0,10);const expanded=[...new Set([...seeds,...clusterKeywords(seeds).slice(0,30).map(x=>x.keyword)])].slice(0,25);const result=await searchBatch(expanded,{country:clean(input.country||"ZA",10),language:clean(input.language||"en",10),locale:clean(input.locale||"en-ZA",20),maxQueries:25});const opportunities=buildSearchOpportunities(domain,competitors,result.results.filter(x=>x&&x.query));return {schema:"izakhono.super-seo.search.v3",generated_at:now(),domain,competitors,seed_keywords:seeds,provider_status:result.provider_status,provider:result.provider,queries:expanded.length,opportunities:opportunities.sort((a,b)=>b.opportunity-a.opportunity),competitor_gaps:opportunities.filter(x=>x.competitor_gap),note:result.provider_status==="not_configured"?"No live SERP data is connected. Scores are not presented as rankings or search-volume claims.":"Live provider observations are shown as returned; metrics are omitted when the provider does not supply them."};}

function validHttpUrl(raw){let u;try{u=new URL(raw)}catch{throw new Error("invalid URL")}if(!["http:","https:"].includes(u.protocol))throw new Error("only HTTP(S) URLs are allowed");const h=u.hostname.toLowerCase();if(h==="localhost"||h.endsWith(".local")||h.endsWith(".internal"))throw new Error("private/local hosts are not allowed");if(net.isIP(h)&&isPrivateIp(h))throw new Error("private IPs are not allowed");u.hash="";return u;}
function isPrivateIp(ip){if(net.isIPv4(ip)){const [a,b]=ip.split(".").map(Number);return a===10||a===127||a===0||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&b===168;}if(net.isIPv6(ip)){const x=ip.toLowerCase();return x==="::1"||x.startsWith("fc")||x.startsWith("fd")||x.startsWith("fe80:")||x==="::";}return true;}
async function assertPublicHost(host){if(net.isIP(host))return;if(host==="localhost"||host.endsWith(".local")||host.endsWith(".internal"))throw new Error("private/local hosts are not allowed");const answers=await dns.lookup(host,{all:true,verbatim:true});if(!answers.length||answers.some(a=>isPrivateIp(a.address)))throw new Error("host resolves to a private address");}
async function fetchSafe(raw,maxBytes=750000){let current=validHttpUrl(raw);for(let hops=0;hops<5;hops++){await assertPublicHost(current.hostname);const ac=new AbortController();const timer=setTimeout(()=>ac.abort(),8000);let r;try{r=await fetch(current,{redirect:"manual",signal:ac.signal,headers:{"user-agent":"IZAKHONO-Super-SEO/2.0"}})}finally{clearTimeout(timer)}if(r.status>=300&&r.status<400&&r.headers.get("location")){current=validHttpUrl(new URL(r.headers.get("location"),current).toString());continue}const buf=Buffer.from(await r.arrayBuffer());if(buf.length>maxBytes)throw new Error("response too large");return {url:current.toString(),status:r.status,type:r.headers.get("content-type")||"",body:buf.toString("utf8")};}throw new Error("too many redirects");}
function stripHtml(s){return s.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/\s+/g," ").trim();}
function attr(tag,name){const m=tag.match(new RegExp(`${name}\\s*=\\s*[\\"']([^\\"']+)`,`i`));return m?m[1].trim():"";}
function extractPage(html,url){const title=(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"").trim();const description=attr(html.match(/<meta[^>]+(?:name|property)=["'](?:description|og:description)["'][^>]*>/i)?.[0]||"","content");const canonical=attr(html.match(/<link[^>]+rel=["'][^"']*canonical[^"']*["'][^>]*>/i)?.[0]||"","href");const robots=attr(html.match(/<meta[^>]+name=["']robots["'][^>]*>/i)?.[0]||"","content");const h1=[...html.matchAll(/<h1[^>]*>([\s\S]*?)<\/h1>/gi)].slice(0,10).map(m=>stripHtml(m[1]));const links=[...html.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>/gi)].map(m=>{try{return new URL(m[1],url).toString()}catch{return null}}).filter(Boolean).map(x=>{const u=new URL(x);u.hash="";return u.toString()});const unique=[...new Set(links)];const text=stripHtml(html);const jsonLd=[...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].length;return {url,status:200,title:clean(title,300),description:clean(description,500),canonical:clean(canonical,500),robots:clean(robots,300),h1,word_count:text?text.split(/\s+/).length:0,links:unique.slice(0,100),json_ld_blocks:jsonLd,noindex:/(^|,|\\s)noindex(,|\\s|$)/i.test(robots)};}
async function crawlSite(input){const start=validHttpUrl(input.url);await assertPublicHost(start.hostname);const maxPages=Math.min(25,Math.max(1,Number(input.max_pages)||10));const sameHost=u=>{try{return(new URL(u)).hostname===start.hostname}catch{return false}};const queue=[{url:start.toString(),depth:0}],seen=new Set(),pages=[],errors=[];let robots="",sitemapUrls=[];for(const pathName of ["/robots.txt","/sitemap.xml"]){try{const r=await fetchSafe(new URL(pathName,start.origin).toString(),300000);if(pathName==="/robots.txt"&&r.status<400)robots=r.body;else if(pathName==="/sitemap.xml"&&r.status<400)sitemapUrls=[...r.body.matchAll(/<loc>\s*([^<]+)\s*<\/loc>/gi)].map(m=>m[1].trim()).filter(sameHost).slice(0,50)}catch(e){errors.push({url:new URL(pathName,start.origin).toString(),error:e.message})}}
while(queue.length&&pages.length<maxPages){const item=queue.shift();if(seen.has(item.url)||!sameHost(item.url))continue;seen.add(item.url);try{const r=await fetchSafe(item.url);if(!/^text\/html/i.test(r.type)&&r.type)continue;if(r.status>=400){errors.push({url:item.url,status:r.status});continue}const p=extractPage(r.body,r.url);p.status=r.status;p.depth=item.depth;pages.push(p);if(item.depth<2){for(const link of p.links){if(sameHost(link)&&!seen.has(link)&&!queue.some(q=>q.url===link))queue.push({url:link,depth:item.depth+1});}}}catch(e){errors.push({url:item.url,error:e.message})}}
for(const u of sitemapUrls){if(pages.length>=maxPages||seen.has(u))break;queue.push({url:u,depth:0});}return {schema:"izakhono.super-seo.crawl.v1",generated_at:now(),start_url:start.toString(),max_pages:maxPages,robots_excerpt:robots.slice(0,4000),sitemap_urls:sitemapUrls,pages,errors,summary:{pages_crawled:pages.length,errors:errors.length,missing_title:pages.filter(p=>!p.title).length,missing_description:pages.filter(p=>!p.description).length,missing_h1:pages.filter(p=>!p.h1.length).length,noindex:pages.filter(p=>p.noindex).length,low_content:pages.filter(p=>p.word_count<300).length}};}
async function body(req){let s="";for await(const c of req){s+=c;if(Buffer.byteLength(s)>262144)throw Object.assign(new Error("payload too large"),{status:413})}try{return JSON.parse(s||"{}")}catch{throw Object.assign(new Error("invalid JSON"),{status:400})}}
function json(res,status,data){res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"});res.end(JSON.stringify(data));}
async function file(res,p){try{const data=await fs.readFile(path.join(PUBLIC,p));const type=p.endsWith(".html")?"text/html":p.endsWith(".js")?"text/javascript":"text/plain";res.writeHead(200,{"content-type":`${type}; charset=utf-8`});res.end(data)}catch{res.writeHead(404);res.end("Not found")}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host||"localhost"}`);if(req.method==="GET"&&u.pathname==="/health")return json(res,200,{ok:true,service:"izakhono-super-seo",version:"0.3.0",time:now()});if(req.method==="GET"&&u.pathname==="/api/dashboard")return json(res,200,{service:"IZAKHONO SUPER SEO",version:"0.3.0",modules:["competitor-intelligence","keyword-opportunity","content-factory","internal-linking","authority-research","live-site-crawler","search-intelligence"],search_provider:providerStatus(),status:"READY_FOR_ANALYSIS",tracking:false});if(req.method==="GET"&&u.pathname==="/api/search/status")return json(res,200,{service:"IZAKHONO SUPER SEO",search_provider:providerStatus(),live_data:false});if(req.method==="POST"&&u.pathname==="/api/search")return json(res,200,await searchIntelligence(await body(req)));if(req.method==="POST"&&u.pathname==="/api/analyze")return json(res,200,analyze(await body(req)));if(req.method==="POST"&&u.pathname==="/api/crawl")return json(res,200,await crawlSite(await body(req)));if(req.method==="GET")return file(res,u.pathname==="/"?"index.html":u.pathname.replace(/^\//,""));res.writeHead(405);res.end("Method not allowed")}catch(e){json(res,e.status||400,{error:e.message||"request failed"})}});
server.listen(PORT,()=>console.log(`IZAKHONO SUPER SEO listening on ${PORT}`));
export { analyze, clusterKeywords, makePlan, extractPage, isPrivateIp, buildSearchOpportunities, searchIntelligence };