type Stmt={bind(...v:unknown[]):Stmt;first<T=any>():Promise<T|null>;all<T=any>():Promise<{results?:T[]}>;run():Promise<unknown>};
type Env={DB:{prepare(sql:string):Stmt}};
function j(d:unknown,s=200){return new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}
function e(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function tok(p:string){return p+"_"+crypto.randomUUID().replaceAll("-","")}
function email(v:string){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
async function schema(env:Env){
 await env.DB.prepare("CREATE TABLE IF NOT EXISTS bidforge_accounts(id TEXT PRIMARY KEY,company_name TEXT NOT NULL,owner_email TEXT NOT NULL,access_token TEXT NOT NULL UNIQUE,plan_price_zar INTEGER NOT NULL DEFAULT 899,status TEXT NOT NULL DEFAULT 'trial',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();
 await env.DB.prepare("CREATE TABLE IF NOT EXISTS bidforge_bids(id TEXT PRIMARY KEY,account_id TEXT NOT NULL,title TEXT NOT NULL,issuer TEXT,deadline TEXT,requirements TEXT,status TEXT NOT NULL DEFAULT 'draft',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();
 await env.DB.prepare("CREATE TABLE IF NOT EXISTS bidforge_items(id TEXT PRIMARY KEY,bid_id TEXT NOT NULL,item_text TEXT NOT NULL,completed INTEGER NOT NULL DEFAULT 0,evidence_note TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();
}
function page(title:string,body:string){return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+e(title)+'</title><style>*{box-sizing:border-box}body{margin:0;background:#100b09;color:#fff8f5;font-family:Inter,system-ui,sans-serif}.wrap{max-width:1120px;margin:auto;padding:28px}.nav{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:48px}.brand{font-weight:950;letter-spacing:.06em}.pill{padding:7px 10px;border-radius:999px;background:#3a1912;color:#ffc6b8;font-size:12px;font-weight:850}.hero{padding:28px 0 55px}.k{letter-spacing:.15em;text-transform:uppercase;font-weight:900;font-size:12px;color:#FF8B73}h1{font-size:clamp(42px,8vw,78px);line-height:.95;margin:14px 0 18px;max-width:950px}h2{margin:0 0 12px}.muted{color:#c7b4ad}p{line-height:1.6}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px}.card{background:#1b1210;border:1px solid #493027;border-radius:20px;padding:20px}.form{display:grid;gap:12px;max-width:650px;margin-top:24px}input,textarea{width:100%;padding:14px 15px;border-radius:12px;border:1px solid #5a3a31;background:#160f0d;color:white;font:inherit}textarea{min-height:150px}button,.btn{border:0;border-radius:12px;background:#FF8B73;color:#1b0905;padding:13px 16px;font-weight:950;font:inherit;cursor:pointer;text-decoration:none;display:inline-flex;justify-content:center}.secondary{background:#2c211e;color:#fff}.metric{font-size:34px;font-weight:950}.small{font-size:12px;color:#aa958e}.row{display:flex;gap:10px;flex-wrap:wrap}.item{display:flex;gap:12px;align-items:flex-start;border-top:1px solid #3a2924;padding:14px 0}.item:first-child{border-top:0}.item button{padding:8px 11px}.done{text-decoration:line-through;opacity:.6}.progress{height:12px;background:#2a1d19;border-radius:999px;overflow:hidden}.bar{height:100%;background:#FF8B73}</style></head><body><div class="wrap">'+body+'</div></body></html>'}
function landing(){
 const b='<div class="nav"><div class="brand">BIDFORGE</div><div class="pill">Founding beta - R899/month</div></div><section class="hero"><div class="k">Tender and RFP workspace for SMEs</div><h1>Turn bid chaos into a repeatable system.</h1><p class="muted" style="font-size:20px;max-width:780px">Create a bid, capture every requirement, track evidence and deadlines, and know exactly how ready your submission is before the due date.</p><form id="signup" class="form"><input name="company_name" placeholder="Company name" maxlength="120" required><input name="owner_email" type="email" placeholder="Owner email" maxlength="180" required><button>Create my BidForge workspace</button></form><div id="m"></div></section><section class="grid"><div class="card"><h2>Capture the opportunity</h2><p class="muted">Store issuer, deadline and raw tender requirements in one place.</p></div><div class="card"><h2>Break it down</h2><p class="muted">BidForge turns requirement lines into a checklist your team can actually work through.</p></div><div class="card"><h2>Know readiness</h2><p class="muted">See a live completion percentage before submission day.</p></div></section><script>const f=document.querySelector("#signup"),m=document.querySelector("#m");f.addEventListener("submit",async x=>{x.preventDefault();m.textContent="Creating workspace...";const d=Object.fromEntries(new FormData(f));try{const r=await fetch("/api/bidforge/accounts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(d)}),z=await r.json();if(!r.ok)throw new Error(z.error||"Signup failed");location.href=z.dashboard_url}catch(err){m.textContent=err.message||String(err)}})</script>';
 return new Response(page("BidForge",b),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}})
}
async function dash(env:Env,url:URL){
 await schema(env);const t=url.searchParams.get("t")||"";const a=await env.DB.prepare("SELECT * FROM bidforge_accounts WHERE access_token=?").bind(t).first<any>();if(!a)return new Response("Workspace not found",{status:404});
 const rr=await env.DB.prepare("SELECT b.*,(SELECT COUNT(*) FROM bidforge_items i WHERE i.bid_id=b.id) items,(SELECT COUNT(*) FROM bidforge_items i WHERE i.bid_id=b.id AND i.completed=1) done FROM bidforge_bids b WHERE b.account_id=? ORDER BY b.created_at DESC").bind(a.id).all<any>();
 const cards=(rr.results||[]).map((x:any)=>{const pct=x.items?Math.round((x.done/x.items)*100):0;return '<div class="card"><div class="k">'+e(x.status)+'</div><h2>'+e(x.title)+'</h2><p class="muted">'+e(x.issuer||"Issuer not set")+'</p><div class="small">Deadline: '+e(x.deadline||"Not set")+'</div><div class="progress" style="margin:14px 0"><div class="bar" style="width:'+pct+'%"></div></div><strong>'+pct+'% ready</strong><div style="margin-top:14px"><a class="btn" href="/bidforge/b/'+encodeURIComponent(x.id)+'?t='+encodeURIComponent(t)+'">Open bid</a></div></div>'}).join("");
 const body='<div class="nav"><div class="brand">BIDFORGE - '+e(a.company_name)+'</div><a class="btn secondary" href="/bidforge">New workspace</a></div><section class="hero"><div class="k">New opportunity</div><h2>Create a bid workspace</h2><form id="newbid" class="form"><input name="title" placeholder="Tender / RFP title" maxlength="160" required><input name="issuer" placeholder="Issuer / buyer" maxlength="160"><input name="deadline" type="datetime-local"><textarea name="requirements" placeholder="Paste requirements, one per line. Each line becomes a checklist item." maxlength="12000" required></textarea><button>Create bid</button></form><div id="m"></div></section><section><div class="k">Active bids</div><div class="grid">'+(cards||'<div class="card"><p class="muted">No bids yet.</p></div>')+'</div></section><script>const f=document.querySelector("#newbid"),m=document.querySelector("#m");f.addEventListener("submit",async x=>{x.preventDefault();m.textContent="Creating bid...";const d=Object.fromEntries(new FormData(f));d.access_token='+JSON.stringify(t)+';try{const r=await fetch("/api/bidforge/bids",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(d)}),z=await r.json();if(!r.ok)throw new Error(z.error||"Could not create bid");location.href=z.bid_url}catch(err){m.textContent=err.message||String(err)}})</script>';
 return new Response(page(a.company_name+" - BidForge",body),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}})
}
async function bid(env:Env,url:URL,id:string){
 await schema(env);const t=url.searchParams.get("t")||"";const b=await env.DB.prepare("SELECT b.*,a.access_token,a.company_name FROM bidforge_bids b JOIN bidforge_accounts a ON a.id=b.account_id WHERE b.id=? AND a.access_token=?").bind(id,t).first<any>();if(!b)return new Response("Bid not found",{status:404});
 const rr=await env.DB.prepare("SELECT * FROM bidforge_items WHERE bid_id=? ORDER BY created_at ASC").bind(id).all<any>();const items=rr.results||[];const done=items.filter((x:any)=>x.completed).length;const pct=items.length?Math.round(done/items.length*100):0;
 const rows=items.map((x:any)=>'<div class="item"><button data-id="'+e(x.id)+'" data-done="'+(x.completed?1:0)+'">'+(x.completed?"Undo":"Done")+'</button><div class="'+(x.completed?"done":"")+'"><strong>'+e(x.item_text)+'</strong>'+(x.evidence_note?('<p class="muted">'+e(x.evidence_note)+'</p>'):"")+'</div></div>').join("");
 const body='<div class="nav"><div class="brand">BIDFORGE</div><a class="btn secondary" href="/bidforge/dashboard?t='+encodeURIComponent(t)+'">Back to dashboard</a></div><section class="hero"><div class="k">'+e(b.company_name)+'</div><h1>'+e(b.title)+'</h1><p class="muted">'+e(b.issuer||"Issuer not set")+'</p><div class="small">Deadline: '+e(b.deadline||"Not set")+'</div><div class="progress" style="margin:18px 0"><div class="bar" style="width:'+pct+'%"></div></div><div class="metric">'+pct+'% ready</div></section><section class="grid"><div class="card"><h2>Requirement checklist</h2>'+rows+'</div><div class="card"><h2>Response structure</h2><p class="muted">Use this sequence for your first draft:</p><ol><li>Executive summary</li><li>Understanding of the requirement</li><li>Proposed solution / methodology</li><li>Experience and evidence</li><li>Delivery plan and timeline</li><li>Commercial / pricing response</li><li>Compliance documents and declarations</li></ol></div></section><script>document.querySelectorAll("[data-id]").forEach(b=>b.onclick=async()=>{const r=await fetch("/api/bidforge/items/"+b.dataset.id+"/toggle",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({access_token:'+JSON.stringify(t)+'})});const z=await r.json();if(!r.ok)return alert(z.error||"Could not update");location.reload()})</script>';
 return new Response(page(b.title+" - BidForge",body),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}})
}
export async function bidForgeRoute(req:Request,env:Env,url:URL):Promise<Response|null>{
 if(url.pathname==="/bidforge"&&req.method==="GET")return landing();
 if(url.pathname==="/bidforge/dashboard"&&req.method==="GET")return dash(env,url);
 const bp=url.pathname.match(/^\/bidforge\/b\/([A-Za-z0-9_]+)$/);if(bp&&req.method==="GET")return bid(env,url,bp[1]);
 if(url.pathname==="/api/bidforge/accounts"&&req.method==="POST"){await schema(env);let b:any={};try{b=await req.json()}catch{return j({ok:false,error:"Expected JSON"},400)}const n=String(b.company_name||"").trim().slice(0,120),em=String(b.owner_email||"").trim().toLowerCase().slice(0,180);if(!n||!email(em))return j({ok:false,error:"Company name and valid email are required."},400);const id=tok("bfa"),t=tok("bft");await env.DB.prepare("INSERT INTO bidforge_accounts(id,company_name,owner_email,access_token) VALUES(?,?,?,?)").bind(id,n,em,t).run();return j({ok:true,dashboard_url:"/bidforge/dashboard?t="+encodeURIComponent(t)},201)}
 if(url.pathname==="/api/bidforge/bids"&&req.method==="POST"){await schema(env);let b:any={};try{b=await req.json()}catch{return j({ok:false,error:"Expected JSON"},400)}const a=await env.DB.prepare("SELECT id FROM bidforge_accounts WHERE access_token=?").bind(String(b.access_token||"")).first<any>();if(!a)return j({ok:false,error:"Workspace not found."},404);const title=String(b.title||"").trim().slice(0,160),reqs=String(b.requirements||"").trim().slice(0,12000);if(!title||!reqs)return j({ok:false,error:"Title and requirements are required."},400);const id=tok("bid");await env.DB.prepare("INSERT INTO bidforge_bids(id,account_id,title,issuer,deadline,requirements) VALUES(?,?,?,?,?,?)").bind(id,a.id,title,String(b.issuer||"").trim().slice(0,160),String(b.deadline||"").trim().slice(0,40),reqs).run();const lines=reqs.split(/\r?\n/).map((x:string)=>x.replace(/^[-*\d.)\s]+/,"").trim()).filter((x:string)=>x.length>2).slice(0,100);for(const line of lines){await env.DB.prepare("INSERT INTO bidforge_items(id,bid_id,item_text) VALUES(?,?,?)").bind(tok("itm"),id,line).run()}return j({ok:true,bid_url:"/bidforge/b/"+encodeURIComponent(id)+"?t="+encodeURIComponent(String(b.access_token||""))},201)}
 const tp=url.pathname.match(/^\/api\/bidforge\/items\/([A-Za-z0-9_]+)\/toggle$/);if(tp&&req.method==="POST"){await schema(env);let b:any={};try{b=await req.json()}catch{return j({ok:false,error:"Expected JSON"},400)}const row=await env.DB.prepare("SELECT i.id,i.completed FROM bidforge_items i JOIN bidforge_bids bd ON bd.id=i.bid_id JOIN bidforge_accounts a ON a.id=bd.account_id WHERE i.id=? AND a.access_token=?").bind(tp[1],String(b.access_token||"")).first<any>();if(!row)return j({ok:false,error:"Checklist item not found."},404);await env.DB.prepare("UPDATE bidforge_items SET completed=? WHERE id=?").bind(row.completed?0:1,row.id).run();return j({ok:true,completed:!row.completed})}
 return null
}