type Stmt={bind(...v:unknown[]):Stmt;first<T=any>():Promise<T|null>;all<T=any>():Promise<{results?:T[]}>;run():Promise<unknown>};
type Env={DB:{prepare(sql:string):Stmt}};
function j(d:unknown,s=200){return new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}
function e(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function email(v:string){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
function http(v:string){try{const u=new URL(v);return u.protocol==="https:"||u.protocol==="http:"}catch{return false}}
function tok(p:string){return p+"_"+crypto.randomUUID().replaceAll("-","")}
function slug(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,48)||"business"}
async function schema(env:Env){
 await env.DB.prepare("CREATE TABLE IF NOT EXISTS reviewloop_accounts(id TEXT PRIMARY KEY,slug TEXT NOT NULL UNIQUE,business_name TEXT NOT NULL,owner_email TEXT NOT NULL,public_review_url TEXT NOT NULL,access_token TEXT NOT NULL UNIQUE,plan_price_zar INTEGER NOT NULL DEFAULT 399,status TEXT NOT NULL DEFAULT 'trial',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();
 await env.DB.prepare("CREATE TABLE IF NOT EXISTS reviewloop_requests(id TEXT PRIMARY KEY,account_id TEXT NOT NULL,customer_name TEXT,request_token TEXT NOT NULL UNIQUE,source TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();
 await env.DB.prepare("CREATE TABLE IF NOT EXISTS reviewloop_feedback(id TEXT PRIMARY KEY,request_id TEXT NOT NULL UNIQUE,rating INTEGER NOT NULL,feedback TEXT,public_review_clicked INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();
}
function page(title:string,body:string){return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+e(title)+'</title><style>*{box-sizing:border-box}body{margin:0;background:#071018;color:#f5f7fb;font-family:Inter,system-ui,sans-serif}.wrap{max-width:1100px;margin:auto;padding:28px}.nav{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:48px}.brand{font-weight:950;letter-spacing:.05em}.pill{padding:7px 10px;border-radius:999px;background:#173229;color:#bff6dc;font-size:12px;font-weight:850}.hero{padding:30px 0 55px}.k{letter-spacing:.15em;text-transform:uppercase;font-weight:900;font-size:12px;color:#57D3A0}h1{font-size:clamp(42px,8vw,82px);line-height:.94;margin:14px 0 20px;max-width:930px}h2{font-size:28px;margin:0 0 12px}p{line-height:1.6}.muted{color:#9eb0c2}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px}.card{background:#0e1a25;border:1px solid #233444;border-radius:22px;padding:22px}.form{display:grid;gap:12px;max-width:600px;margin-top:24px}input,textarea{width:100%;border-radius:12px;border:1px solid #304254;background:#0b1722;color:white;padding:14px 15px;font:inherit}textarea{min-height:120px}button,.btn{border:0;border-radius:12px;background:#57D3A0;color:#05120d;padding:13px 16px;font-weight:950;font:inherit;cursor:pointer;text-decoration:none;display:inline-flex;justify-content:center}.secondary{background:#182738;color:#e6eef7}.row{display:flex;gap:10px;flex-wrap:wrap}.metric{font-size:34px;font-weight:950}.small{font-size:12px;color:#8fa0b0}.msg{min-height:24px;margin-top:10px}.stars{display:flex;gap:8px;flex-wrap:wrap;margin:22px 0}.star{font-size:22px;padding:12px 16px;border-radius:14px;border:1px solid #33485c;background:#0d1b27;color:#ffd66b}.copy{word-break:break-all;background:#07131d;padding:12px;border:1px dashed #395065;border-radius:10px}</style></head><body><div class="wrap">'+body+'</div></body></html>'}
function landing(){
 const body='<div class="nav"><div class="brand">REVIEWLOOP</div><div class="pill">Founding beta - R399/month</div></div><section class="hero"><div class="k">Reputation workflow for local businesses</div><h1>Ask every customer. Learn faster. Earn more trust.</h1><p class="muted" style="font-size:20px;max-width:760px">ReviewLoop gives businesses a simple review-request link, tracks responses, captures private service feedback, and gives every customer the same opportunity to leave an honest public review.</p><form id="signup" class="form"><input name="business_name" placeholder="Business name" maxlength="120" required><input name="owner_email" type="email" placeholder="Owner email" maxlength="180" required><input name="public_review_url" type="url" placeholder="Google / Facebook / Trustpilot review URL" maxlength="1000" required><button>Create my ReviewLoop</button></form><div id="msg" class="msg"></div></section><section class="grid"><div class="card"><h2>1. Create a request</h2><p class="muted">Generate a customer link after a completed job or visit.</p></div><div class="card"><h2>2. Hear the truth</h2><p class="muted">Capture ratings and optional private service feedback.</p></div><div class="card"><h2>3. Build public proof</h2><p class="muted">Every respondent can continue to your public review page. No review gating.</p></div></section><script>const f=document.querySelector("#signup"),m=document.querySelector("#msg");f.addEventListener("submit",async x=>{x.preventDefault();m.textContent="Creating workspace...";const d=Object.fromEntries(new FormData(f));try{const r=await fetch("/api/reviewloop/businesses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(d)}),z=await r.json();if(!r.ok)throw new Error(z.error||"Signup failed");location.href=z.dashboard_url}catch(err){m.textContent=err.message||String(err)}})</script>';
 return new Response(page("ReviewLoop",body),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}})
}
async function dash(env:Env,url:URL){
 await schema(env);const access=url.searchParams.get("t")||"";
 const a=await env.DB.prepare("SELECT a.*,(SELECT COUNT(*) FROM reviewloop_requests r WHERE r.account_id=a.id) requests,(SELECT COUNT(*) FROM reviewloop_feedback f JOIN reviewloop_requests r ON r.id=f.request_id WHERE r.account_id=a.id) responses,COALESCE((SELECT ROUND(AVG(f.rating),1) FROM reviewloop_feedback f JOIN reviewloop_requests r ON r.id=f.request_id WHERE r.account_id=a.id),0) avg_rating,(SELECT COUNT(*) FROM reviewloop_feedback f JOIN reviewloop_requests r ON r.id=f.request_id WHERE r.account_id=a.id AND f.public_review_clicked=1) public_clicks FROM reviewloop_accounts a WHERE a.access_token=?").bind(access).first<any>();
 if(!a)return new Response("Workspace not found",{status:404});
 const rr=await env.DB.prepare("SELECT r.customer_name,r.created_at,f.rating,f.feedback,f.public_review_clicked FROM reviewloop_requests r LEFT JOIN reviewloop_feedback f ON f.request_id=r.id WHERE r.account_id=? ORDER BY r.created_at DESC LIMIT 20").bind(a.id).all<any>();
 const rows=(rr.results||[]).map((x:any)=>'<div class="card"><strong>'+e(x.customer_name||"Customer")+'</strong><div class="small">'+e(x.created_at)+'</div><p>'+(x.rating?("Rating: <strong>"+e(x.rating)+"/5</strong>"):"Awaiting response")+'</p>'+(x.feedback?('<p class="muted">'+e(x.feedback)+'</p>'):"")+'<div class="small">Public-review click: '+(x.public_review_clicked?"Yes":"No")+"</div></div>").join("");
 const body='<div class="nav"><div class="brand">REVIEWLOOP - '+e(a.business_name)+'</div><a class="btn secondary" href="/reviewloop">New workspace</a></div><section class="grid"><div class="card"><div class="small">Requests</div><div class="metric">'+e(a.requests)+'</div></div><div class="card"><div class="small">Responses</div><div class="metric">'+e(a.responses)+'</div></div><div class="card"><div class="small">Average rating</div><div class="metric">'+e(a.avg_rating||0)+'</div></div><div class="card"><div class="small">Public-review clicks</div><div class="metric">'+e(a.public_clicks)+'</div></div></section><section class="hero"><div class="k">Create customer request</div><h2>Generate a review link</h2><form id="req" class="form"><input name="customer_name" placeholder="Customer name (optional)" maxlength="120"><button>Generate request</button></form><div id="result" class="msg"></div></section><section><div class="k">Recent activity</div><div class="grid">'+(rows||'<div class="card"><p class="muted">No requests yet.</p></div>')+'</div></section><script>const f=document.querySelector("#req"),o=document.querySelector("#result");f.addEventListener("submit",async x=>{x.preventDefault();o.textContent="Generating...";const customer_name=new FormData(f).get("customer_name");try{const r=await fetch("/api/reviewloop/requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({access_token:'+JSON.stringify(access)+',customer_name})}),z=await r.json();if(!r.ok)throw new Error(z.error||"Could not create request");o.innerHTML="<div class=\"card\"><strong>Customer link</strong><div class=\"copy\">"+z.request_url+"</div><p class=\"muted\">"+z.suggested_message+"</p><div class=\"row\"><button id=\"cl\">Copy link</button><button id=\"cm\" class=\"secondary\">Copy message</button></div></div>";document.querySelector("#cl").onclick=()=>navigator.clipboard.writeText(z.request_url);document.querySelector("#cm").onclick=()=>navigator.clipboard.writeText(z.suggested_message);f.reset()}catch(err){o.textContent=err.message||String(err)}})</script>';
 return new Response(page(a.business_name+" - ReviewLoop",body),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}})
}
async function customer(env:Env,t:string){
 await schema(env);const r=await env.DB.prepare("SELECT r.id,r.customer_name,a.business_name FROM reviewloop_requests r JOIN reviewloop_accounts a ON a.id=r.account_id WHERE r.request_token=?").bind(t).first<any>();if(!r)return new Response("Request not found",{status:404});
 const old=await env.DB.prepare("SELECT rating FROM reviewloop_feedback WHERE request_id=?").bind(r.id).first<any>();if(old)return new Response(page("Thank you",'<section class="hero"><div class="k">'+e(r.business_name)+'</div><h1>Thank you for your feedback.</h1><p class="muted">Your response has already been recorded.</p></section>'),{headers:{"content-type":"text/html; charset=utf-8"}});
 const body='<div class="nav"><div class="brand">REVIEWLOOP</div></div><section class="hero"><div class="k">'+e(r.business_name)+'</div><h1>How was your experience?</h1><p class="muted">'+(r.customer_name?("Hi "+e(r.customer_name)+". "):"")+'Your honest feedback helps this business improve.</p><form id="rate" class="form"><input type="hidden" name="rating" id="rating"><div class="stars"><button class="star" type="button" data-r="1">1 star</button><button class="star" type="button" data-r="2">2 stars</button><button class="star" type="button" data-r="3">3 stars</button><button class="star" type="button" data-r="4">4 stars</button><button class="star" type="button" data-r="5">5 stars</button></div><textarea name="feedback" placeholder="Optional private feedback" maxlength="2000"></textarea><button>Submit feedback</button></form><div id="msg" class="msg"></div></section><script>const q=document.querySelector("#rating");document.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>{q.value=b.dataset.r;document.querySelectorAll("[data-r]").forEach(x=>x.style.outline="none");b.style.outline="3px solid #57D3A0"});const f=document.querySelector("#rate"),m=document.querySelector("#msg");f.addEventListener("submit",async x=>{x.preventDefault();if(!q.value){m.textContent="Choose a rating first.";return}const d=Object.fromEntries(new FormData(f));try{const r=await fetch("/api/reviewloop/respond/'+encodeURIComponent(t)+'",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(d)}),z=await r.json();if(!r.ok)throw new Error(z.error||"Could not submit");document.querySelector(".hero").innerHTML="<div class=\"k\">'+e(r.business_name)+'</div><h1>Thank you.</h1><p class=\"muted\">Your feedback has been recorded.</p><a class=\"btn\" href=\""+z.public_review_url+"\">Leave an honest public review</a><p class=\"small\">The public review option is available to every respondent, regardless of rating.</p>"}catch(err){m.textContent=err.message||String(err)}})</script>';
 return new Response(page("Review "+r.business_name,body),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}})
}
export async function reviewLoopRoute(req:Request,env:Env,url:URL):Promise<Response|null>{
 if(url.pathname==="/reviewloop"&&req.method==="GET")return landing();
 if(url.pathname==="/reviewloop/dashboard"&&req.method==="GET")return dash(env,url);
 const cp=url.pathname.match(/^\/reviewloop\/r\/([A-Za-z0-9_]+)$/);if(cp&&req.method==="GET")return customer(env,cp[1]);
 if(url.pathname==="/api/reviewloop/businesses"&&req.method==="POST"){await schema(env);let b:any={};try{b=await req.json()}catch{return j({ok:false,error:"Expected JSON"},400)}const n=String(b.business_name||"").trim().slice(0,120),em=String(b.owner_email||"").trim().toLowerCase().slice(0,180),pu=String(b.public_review_url||"").trim().slice(0,1000);if(!n||!email(em)||!http(pu))return j({ok:false,error:"Business name, valid email and valid public review URL are required."},400);const id=tok("rlb"),ac=tok("rla");let sl=slug(n);for(let i=0;i<4;i++){try{await env.DB.prepare("INSERT INTO reviewloop_accounts(id,slug,business_name,owner_email,public_review_url,access_token) VALUES(?,?,?,?,?,?)").bind(id,sl,n,em,pu,ac).run();return j({ok:true,dashboard_url:"/reviewloop/dashboard?t="+encodeURIComponent(ac)},201)}catch{sl=slug(n)+"-"+crypto.randomUUID().slice(0,6)}}return j({ok:false,error:"Could not create workspace."},500)}
 if(url.pathname==="/api/reviewloop/requests"&&req.method==="POST"){await schema(env);let b:any={};try{b=await req.json()}catch{return j({ok:false,error:"Expected JSON"},400)}const a=await env.DB.prepare("SELECT id,business_name FROM reviewloop_accounts WHERE access_token=?").bind(String(b.access_token||"")).first<any>();if(!a)return j({ok:false,error:"Workspace not found."},404);const rt=tok("rlr"),cn=String(b.customer_name||"").trim().slice(0,120);await env.DB.prepare("INSERT INTO reviewloop_requests(id,account_id,customer_name,request_token,source) VALUES(?,?,?,?,?)").bind(tok("req"),a.id,cn,rt,"dashboard").run();const u=url.origin+"/reviewloop/r/"+encodeURIComponent(rt),msg=(cn?("Hi "+cn+", "):"")+"thanks for choosing "+a.business_name+". Would you share a quick, honest review of your experience? "+u;return j({ok:true,request_url:u,suggested_message:msg})}
 const rp=url.pathname.match(/^\/api\/reviewloop\/respond\/([A-Za-z0-9_]+)$/);if(rp&&req.method==="POST"){await schema(env);let b:any={};try{b=await req.json()}catch{return j({ok:false,error:"Expected JSON"},400)}const rating=Number(b.rating);if(!Number.isInteger(rating)||rating<1||rating>5)return j({ok:false,error:"Rating must be 1 to 5."},400);const r=await env.DB.prepare("SELECT r.id,a.public_review_url FROM reviewloop_requests r JOIN reviewloop_accounts a ON a.id=r.account_id WHERE r.request_token=?").bind(rp[1]).first<any>();if(!r)return j({ok:false,error:"Review request not found."},404);try{await env.DB.prepare("INSERT INTO reviewloop_feedback(id,request_id,rating,feedback) VALUES(?,?,?,?)").bind(tok("fb"),r.id,rating,String(b.feedback||"").trim().slice(0,2000)).run()}catch{return j({ok:false,error:"Feedback has already been submitted."},409)}return j({ok:true,public_review_url:url.origin+"/reviewloop/out/"+encodeURIComponent(rp[1])})}
 const op=url.pathname.match(/^\/reviewloop\/out\/([A-Za-z0-9_]+)$/);if(op&&req.method==="GET"){await schema(env);const r=await env.DB.prepare("SELECT r.id,a.public_review_url FROM reviewloop_requests r JOIN reviewloop_accounts a ON a.id=r.account_id WHERE r.request_token=?").bind(op[1]).first<any>();if(!r)return new Response("Not found",{status:404});await env.DB.prepare("UPDATE reviewloop_feedback SET public_review_clicked=1 WHERE request_id=?").bind(r.id).run();return Response.redirect(r.public_review_url,302)}
 return null
}