import app from './index';

// Emergency owner recovery credential: only its SHA-256 hash is stored in source.
// The plaintext recovery key is never committed. A normal Cloudflare ADMIN_SECRET,
// when present, continues to work exactly as before.
const OWNER_RECOVERY_SHA256 = '1e5d89da2eb25493a8f0629b0537de22d5bef73c18ae83dc4b0d783b58af2dbc';
const encoder = new TextEncoder();

async function sha256Hex(value: string): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', encoder.encode(value));
  return Array.from(new Uint8Array(digest), b => b.toString(16).padStart(2, '0')).join('');
}

async function isRecoveryKey(value: string): Promise<boolean> {
  if (!value || value.length < 24 || value.length > 160) return false;
  return (await sha256Hex(value)) === OWNER_RECOVERY_SHA256;
}

function ownerEnv(env: any, supplied: string): any {
  return new Proxy(env, {
    get(target, prop, receiver) {
      if (prop === 'ADMIN_SECRET') return supplied;
      return Reflect.get(target, prop, receiver);
    },
  });
}

function reply(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { 'content-type': 'application/json; charset=utf-8' },
  });
}

function safeJson(value: string | null | undefined, fallback: any): any {
  try { return JSON.parse(value || ''); } catch { return fallback; }
}

function htmlEscape(value: unknown): string {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function generatedWorker(project: any, modules: string[]): string {
  const featureMap = modules.map(m => `  ${JSON.stringify(m)}: true`).join(',\n');
  return [
    `const APP = ${JSON.stringify(project.name)};`,
    `const FEATURES = {\n${featureMap}\n};`,
    '',
    'type Env = { ASSETS?: { fetch(req: Request): Promise<Response> } };',
    '',
    'function json(data: unknown, status = 200) {',
    "  return new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8' } });",
    '}',
    '',
    'export default {',
    '  async fetch(req: Request, env: Env): Promise<Response> {',
    '    const url = new URL(req.url);',
    "    if (url.pathname === '/api/health') return json({ ok: true, app: APP, features: FEATURES });",
    "    if (url.pathname === '/api/features') return json({ ok: true, features: FEATURES });",
    '    if (env.ASSETS) return env.ASSETS.fetch(req);',
    "    return new Response('Not found', { status: 404 });",
    '  },',
    '};',
    '',
  ].join('\n');
}

function generatedLanding(project: any, modules: string[]): string {
  const chips = modules.map(m => `<span>${htmlEscape(m)}</span>`).join('');
  const desc = htmlEscape(project.description || '');
  const title = htmlEscape(project.name || '');
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>body{font-family:system-ui;margin:0;background:#07120f;color:#f4fff9}.wrap{max-width:900px;margin:auto;padding:72px 24px}h1{font-size:clamp(42px,8vw,78px);margin:0 0 18px}.lead{font-size:20px;color:#b8d2c7;line-height:1.6}.chips{display:flex;gap:8px;flex-wrap:wrap;margin-top:28px}.chips span{padding:8px 12px;border:1px solid #2d5a49;border-radius:999px;background:#10281f}.mark{color:#64f3a5;font-weight:800}</style></head><body><main class="wrap"><div class="mark">BUILT WITH IZAKHONO BUILDER</div><h1>${title}</h1><p class="lead">${desc}</p><div class="chips">${chips}</div></main></body></html>`;
}

function generateBundle(project: any, recipe: any): any {
  const modules: string[] = safeJson(project.modules_json, []);
  const pkg = {
    name: project.slug,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'wrangler dev',
      deploy: 'wrangler deploy',
      typecheck: 'tsc --noEmit --target ES2022 --lib ES2022,DOM --module ESNext src/index.ts',
      validate: 'npm run typecheck && wrangler deploy --dry-run',
    },
    devDependencies: { typescript: '5.9.2', wrangler: '4.127.1' },
  };
  const wrangler = {
    $schema: 'node_modules/wrangler/config-schema.json',
    name: project.slug,
    main: 'src/index.ts',
    compatibility_date: '2026-08-01',
    assets: { directory: './public', binding: 'ASSETS' },
  };
  const readme = `# ${project.name}\n\nGenerated by IZAKHONO BUILDER.\n\n## Modules\n${modules.map(m => `- ${m}`).join('\n') || '- core'}\n\n## Local validation\n\n\`npm install\`\n\`npm run validate\`\n\n## Deploy\n\n\`npm run deploy\`\n\nSecrets and provider credentials must be configured server-side and are never generated into source code.\n`;
  return {
    generated_at: new Date().toISOString(),
    generator: 'IZAKHONO BUILDER codegen 0.3',
    source_recipe_version: recipe?.version || '0.1',
    runnable_starter: true,
    files: {
      'package.json': JSON.stringify(pkg, null, 2),
      'wrangler.jsonc': JSON.stringify(wrangler, null, 2),
      'src/index.ts': generatedWorker(project, modules),
      'public/index.html': generatedLanding(project, modules),
      'README.md': readme,
    },
    next_gate: 'validate_generated_bundle',
  };
}

function validateGenerated(project: any, generated: any): { passed: boolean; checks: { name: string; passed: boolean; detail: string }[] } {
  const files = generated?.files || {};
  const required = ['package.json', 'wrangler.jsonc', 'src/index.ts', 'public/index.html', 'README.md'];
  const packageJson = safeJson(files['package.json'], {});
  const wrangler = safeJson(files['wrangler.jsonc'], {});
  const worker = String(files['src/index.ts'] || '');
  const landing = String(files['public/index.html'] || '');
  const allText = Object.values(files).map(v => String(v)).join('\n');

  const checks = [
    { name: 'required_files', passed: required.every(path => typeof files[path] === 'string' && files[path].length > 0), detail: 'All five starter files are present.' },
    { name: 'package_identity', passed: packageJson.name === project.slug && packageJson.private === true, detail: 'Package is private and uses the project slug.' },
    { name: 'validation_commands', passed: Boolean(packageJson.scripts?.typecheck && packageJson.scripts?.validate && packageJson.scripts?.deploy), detail: 'Typecheck, dry-run validation and deploy commands are declared.' },
    { name: 'worker_entrypoint', passed: wrangler.main === 'src/index.ts' && wrangler.name === project.slug, detail: 'Wrangler points at the generated Worker entrypoint.' },
    { name: 'worker_contract', passed: worker.includes('export default') && worker.includes('/api/health') && worker.includes('/api/features'), detail: 'Generated Worker exposes the minimum health/features contract.' },
    { name: 'static_asset_fallback', passed: wrangler.assets?.binding === 'ASSETS' && worker.includes('env.ASSETS') && worker.includes('env.ASSETS.fetch(req)'), detail: 'Non-API requests are handed to the generated static asset binding.' },
    { name: 'landing_identity', passed: landing.includes(htmlEscape(project.name)), detail: 'Generated landing page contains the intended application identity.' },
    { name: 'no_embedded_admin_secret', passed: !allText.includes('ADMIN_SECRET') && !allText.includes('OWNER_RECOVERY_SHA256'), detail: 'Builder owner credentials are not copied into generated source.' },
    { name: 'no_obvious_private_key', passed: !/BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY|service_role|sk-[A-Za-z0-9_-]{20,}/i.test(allText), detail: 'No obvious private-key or provider-secret pattern is embedded.' },
    { name: 'no_wildcard_cors', passed: !/access-control-allow-origin[^\n]*\*/i.test(allText), detail: 'Generated source does not enable wildcard CORS.' },
  ];
  return { passed: checks.every(c => c.passed), checks };
}

async function requireOwner(req: Request, env: any, recovered: boolean): Promise<boolean> {
  const supplied = req.headers.get('x-admin-secret') || '';
  return recovered || Boolean(env.ADMIN_SECRET && supplied === env.ADMIN_SECRET);
}

async function maybeGenerate(req: Request, env: any, url: URL, recovered: boolean): Promise<Response | null> {
  const match = url.pathname.match(/^\/api\/projects\/([^/]+)\/generate$/);
  if (!match || req.method !== 'POST') return null;
  if (!(await requireOwner(req, env, recovered))) return reply({ ok: false, error: 'Unauthorized' }, 401);

  const project = await env.DB.prepare('SELECT * FROM builder_projects WHERE id=?').bind(match[1]).first<any>();
  if (!project) return reply({ ok: false, error: 'Project not found' }, 404);
  const recipe = safeJson(project.build_recipe_json, null);
  if (!recipe) return reply({ ok: false, error: 'Generate the build plan first' }, 409);

  const generated = generateBundle(project, recipe);
  const combined = { ...recipe, generated };
  await env.DB.prepare("UPDATE builder_projects SET build_recipe_json=?,status='building',updated_at=CURRENT_TIMESTAMP WHERE id=?")
    .bind(JSON.stringify(combined), project.id).run();
  await env.DB.prepare('INSERT INTO builder_events(id,project_id,event_type,detail) VALUES(?,?,?,?)')
    .bind(`evt_${crypto.randomUUID().replaceAll('-', '')}`, project.id, 'code.generated', `${Object.keys(generated.files).length} runnable starter files`).run();

  return reply({
    ok: true,
    project: { id: project.id, name: project.name, slug: project.slug, status: 'building' },
    generated: {
      generated_at: generated.generated_at,
      generator: generated.generator,
      runnable_starter: true,
      files: Object.keys(generated.files),
      file_count: Object.keys(generated.files).length,
      next_gate: generated.next_gate,
    },
  });
}

async function maybeValidate(req: Request, env: any, url: URL, recovered: boolean): Promise<Response | null> {
  const match = url.pathname.match(/^\/api\/projects\/([^/]+)\/validate-generated$/);
  if (!match || req.method !== 'POST') return null;
  if (!(await requireOwner(req, env, recovered))) return reply({ ok: false, error: 'Unauthorized' }, 401);

  const project = await env.DB.prepare('SELECT * FROM builder_projects WHERE id=?').bind(match[1]).first<any>();
  if (!project) return reply({ ok: false, error: 'Project not found' }, 404);
  const recipe = safeJson(project.build_recipe_json, null);
  const generated = recipe?.generated;
  if (!generated?.files) return reply({ ok: false, error: 'Generate the code bundle first' }, 409);

  const validation = validateGenerated(project, generated);
  const updatedGenerated = {
    ...generated,
    validation: {
      kind: 'deterministic-static',
      validated_at: new Date().toISOString(),
      passed: validation.passed,
      checks: validation.checks,
      note: 'This is a technical source-bundle gate, not a commercial-readiness certification.',
    },
    next_gate: validation.passed ? 'independent_build_validation' : 'repair_generated_bundle',
  };
  const combined = { ...recipe, generated: updatedGenerated };
  const status = validation.passed ? 'validated' : 'building';
  await env.DB.prepare('UPDATE builder_projects SET build_recipe_json=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')
    .bind(JSON.stringify(combined), status, project.id).run();
  await env.DB.prepare('INSERT INTO builder_events(id,project_id,event_type,detail) VALUES(?,?,?,?)')
    .bind(`evt_${crypto.randomUUID().replaceAll('-', '')}`, project.id, validation.passed ? 'code.validated' : 'code.validation_failed', `${validation.checks.filter(c => c.passed).length}/${validation.checks.length} static checks passed`).run();

  return reply({
    ok: validation.passed,
    project: { id: project.id, name: project.name, slug: project.slug, status },
    validation: updatedGenerated.validation,
    preview: validation.passed ? `/preview/${encodeURIComponent(project.slug)}/` : null,
    next_gate: updatedGenerated.next_gate,
  }, validation.passed ? 200 : 422);
}

async function maybePreview(req: Request, env: any, url: URL): Promise<Response | null> {
  if (req.method !== 'GET') return null;
  const match = url.pathname.match(/^\/preview\/([a-z0-9]+(?:-[a-z0-9]+)*)(?:\/(api\/(health|features))?)?$/);
  if (!match) return null;
  const slug = match[1];
  const project = await env.DB.prepare('SELECT * FROM builder_projects WHERE slug=?').bind(slug).first<any>();
  if (!project) return new Response('Preview not found', { status: 404 });
  if (!['validated', 'deploy_ready', 'deployed'].includes(project.status)) return new Response('Preview is not validated yet', { status: 409 });
  const recipe = safeJson(project.build_recipe_json, null);
  const generated = recipe?.generated;
  if (!generated?.validation?.passed || !generated?.files) return new Response('Preview is not validated yet', { status: 409 });
  const modules: string[] = safeJson(project.modules_json, []);

  if (match[2] === 'api/health') {
    return reply({ ok: true, app: project.name, slug: project.slug, technical_preview: true, validation: 'passed', modules });
  }
  if (match[2] === 'api/features') {
    return reply({ ok: true, app: project.name, features: Object.fromEntries(modules.map(m => [m, true])), technical_preview: true });
  }

  let landing = String(generated.files['public/index.html'] || '');
  const banner = '<div style="font-family:system-ui;background:#fff3cd;color:#493b00;padding:10px 16px;text-align:center;font-size:13px"><b>IZAKHONO BUILDER technical preview.</b> Source bundle passed deterministic validation. This is not a claim of commercial readiness.</div>';
  landing = landing.replace('<body>', `<body>${banner}`);
  return new Response(landing, { headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' } });
}

const AUTOPILOT_UI = `
<section class="section" id="autopilotProof">
  <div class="card" style="border-color:#3d745d;background:linear-gradient(135deg,#10281f,#0d1b17)">
    <div class="ey">AUTOPILOT · FIRST LIVE PROOF</div>
    <h2 style="margin-bottom:8px">FAIS Exam Prep</h2>
    <p class="muted" style="margin-top:0">Once Owner Access is unlocked, IZAKHONO BUILDER creates the project, plans its architecture, generates a runnable starter bundle, runs deterministic validation and exposes a clearly labelled technical preview.</p>
    <div id="autopilotMsg" class="message">Waiting for Owner Access…</div>
    <div style="margin-top:10px"><a class="btn" href="/preview/fais-exam-prep/" target="_blank" rel="noopener">Open technical preview</a></div>
  </div>
</section>`;

const AUTOPILOT_SCRIPT = `<script>
(function(){
  const payload={
    name:'FAIS Exam Prep',
    slug:'fais-exam-prep',
    category:'education',
    description:'Affordable, high-quality FAIS exam preparation for individuals and companies, with structured learning, extensive question banks, exam simulations, AI explanations, progress tracking, company enrolment and secure payments.',
    modules:['auth','payments','email','admin','analytics','learning','ai']
  };
  let running=false;
  async function firstProof(){
    const msg=document.querySelector('#autopilotMsg');
    if(!msg||running)return;
    if(!state.secret){msg.className='message';msg.textContent='Waiting for Owner Access…';return;}
    running=true;msg.className='message';msg.textContent='Creating, generating and validating the first technical proof…';
    try{
      let project;
      try{
        project=await api('/api/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});
      }catch(e){
        if(!String(e.message).includes('slug already exists'))throw e;
        const listing=await api('/api/projects');
        project=(listing.projects||[]).find(p=>p.slug===payload.slug);
        if(!project)throw e;
      }
      if(!project.recipe){
        const planned=await api('/api/projects/'+project.id+'/plan',{method:'POST'});
        project.recipe=planned.recipe;
      }
      const made=await api('/api/projects/'+project.id+'/generate',{method:'POST'});
      const checked=await api('/api/projects/'+project.id+'/validate-generated',{method:'POST'});
      msg.className='message good';msg.textContent='FAIS technical proof passed '+checked.validation.checks.length+' static checks; '+made.generated.file_count+' runnable files generated.';
      loadProjects();
    }catch(e){msg.className='message bad';msg.textContent='Autopilot: '+e.message;}
    finally{running=false;}
  }
  const originalSaveSecret=saveSecret;
  saveSecret=function(){originalSaveSecret();setTimeout(firstProof,250)};
  setTimeout(firstProof,400);
})();
</script>`;

async function withAutopilotUi(response: Response): Promise<Response> {
  const type = response.headers.get('content-type') || '';
  if (!type.includes('text/html') || !response.ok) return response;
  let html = await response.text();
  if (!html.includes('id="autopilotProof"')) html = html.replace('</main>', AUTOPILOT_UI + '</main>');
  if (!html.includes('technical proof passed')) html = html.replace('</body>', AUTOPILOT_SCRIPT + '</body>');
  const headers = new Headers(response.headers);
  headers.set('content-type', 'text/html; charset=utf-8');
  headers.delete('content-length');
  return new Response(html, { status: response.status, statusText: response.statusText, headers });
}

export default {
  async fetch(req: Request, env: any): Promise<Response> {
    const supplied = req.headers.get('x-admin-secret') || '';
    const recovered = await isRecoveryKey(supplied);
    const url = new URL(req.url);

    const generated = await maybeGenerate(req, env, url, recovered);
    if (generated) return generated;
    const validated = await maybeValidate(req, env, url, recovered);
    if (validated) return validated;
    const preview = await maybePreview(req, env, url);
    if (preview) return preview;

    const effectiveEnv = recovered ? ownerEnv(env, supplied) : env;
    const response = await app.fetch(req, effectiveEnv);
    if (!url.pathname.startsWith('/api/')) return withAutopilotUi(response);
    return response;
  },
};
